//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
/// Process the [events](crate::state::AnyEvent) at the given positions.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ConsumeGivenEvents {
    pub slots: Vec<u64>,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ConsumeGivenEventsInstructionAccounts {
    pub consume_events_admin: Option<solana_pubkey::Pubkey>,
    pub market: solana_pubkey::Pubkey,
    pub event_heap: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ConsumeGivenEvents {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [209, 227, 54, 4, 109, 172, 41, 71] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for ConsumeGivenEvents {
    type ArrangedAccounts = ConsumeGivenEventsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let consume_events_admin = next_account(&mut iter);
        let market = next_account(&mut iter)?;
        let event_heap = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ConsumeGivenEventsInstructionAccounts {
            consume_events_admin,
            market,
            event_heap,
            remaining: remaining.to_vec(),
        })
    }
}
