//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::U64, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CancelDustOrderParams")]
pub struct CancelDustOrderParamsGraphQL {
    pub one_usd_input_mint_amount: U64,
}

impl From<crate::types::CancelDustOrderParams> for CancelDustOrderParamsGraphQL {
    fn from(original: crate::types::CancelDustOrderParams) -> Self {
        Self {
            one_usd_input_mint_amount: carbon_core::graphql::primitives::U64(
                original.one_usd_input_mint_amount,
            ),
        }
    }
}
