//! This code was AUTOGENERATED using the Codama library.
use {crate::types::FeeTier, carbon_core::deserialize::CarbonDeserialize, solana_pubkey::Pubkey};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct UpsertStableFeeTiersEventEvent {
    pub timestamp: i64,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub admin: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub fee_config: Pubkey,
    pub stable_fee_tiers: Vec<FeeTier>,
    pub offset: u8,
}

impl CarbonDeserialize for UpsertStableFeeTiersEventEvent {
    const DISCRIMINATOR: &'static [u8] = &[232, 237, 237, 52, 98, 146, 73, 243];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
