//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "Key")]
pub enum KeyGraphQL {
    Uninitialized,
    EditionV1,
    MasterEditionV1,
    ReservationListV1,
    MetadataV1,
    ReservationListV2,
    MasterEditionV2,
    EditionMarker,
    UseAuthorityRecord,
    CollectionAuthorityRecord,
    TokenOwnedEscrow,
    TokenRecord,
    MetadataDelegate,
    EditionMarkerV2,
    HolderDelegate,
}

impl From<crate::types::Key> for KeyGraphQL {
    fn from(original: crate::types::Key) -> Self {
        match original {
            crate::types::Key::Uninitialized => Self::Uninitialized,
            crate::types::Key::EditionV1 => Self::EditionV1,
            crate::types::Key::MasterEditionV1 => Self::MasterEditionV1,
            crate::types::Key::ReservationListV1 => Self::ReservationListV1,
            crate::types::Key::MetadataV1 => Self::MetadataV1,
            crate::types::Key::ReservationListV2 => Self::ReservationListV2,
            crate::types::Key::MasterEditionV2 => Self::MasterEditionV2,
            crate::types::Key::EditionMarker => Self::EditionMarker,
            crate::types::Key::UseAuthorityRecord => Self::UseAuthorityRecord,
            crate::types::Key::CollectionAuthorityRecord => Self::CollectionAuthorityRecord,
            crate::types::Key::TokenOwnedEscrow => Self::TokenOwnedEscrow,
            crate::types::Key::TokenRecord => Self::TokenRecord,
            crate::types::Key::MetadataDelegate => Self::MetadataDelegate,
            crate::types::Key::EditionMarkerV2 => Self::EditionMarkerV2,
            crate::types::Key::HolderDelegate => Self::HolderDelegate,
        }
    }
}
