//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    instruction::InstructionMetadata,
    postgres::{metadata::InstructionRowMetadata, primitives::U64},
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct RemoveLiquiditySingleSideRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub pool_token_amount: U64,
    pub minimum_out_amount: U64,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl RemoveLiquiditySingleSideRow {
    pub fn from_parts(
        source: crate::instructions::remove_liquidity_single_side::RemoveLiquiditySingleSide,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            pool_token_amount: source.pool_token_amount.into(),
            minimum_out_amount: source.minimum_out_amount.into(),
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<RemoveLiquiditySingleSideRow>
    for crate::instructions::remove_liquidity_single_side::RemoveLiquiditySingleSide
{
    type Error = carbon_core::error::Error;
    fn try_from(source: RemoveLiquiditySingleSideRow) -> Result<Self, Self::Error> {
        Ok(Self {
            pool_token_amount: *source.pool_token_amount,
            minimum_out_amount: *source.minimum_out_amount,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::remove_liquidity_single_side::RemoveLiquiditySingleSide
{
    fn table() -> &'static str {
        "remove_liquidity_single_side_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "pool_token_amount",
            "minimum_out_amount",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RemoveLiquiditySingleSideRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO remove_liquidity_single_side_instruction (
                "pool_token_amount",
                "minimum_out_amount",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#,
        )
        .bind(&self.pool_token_amount)
        .bind(&self.minimum_out_amount)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RemoveLiquiditySingleSideRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO remove_liquidity_single_side_instruction (
                "pool_token_amount",
                "minimum_out_amount",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "pool_token_amount" = EXCLUDED."pool_token_amount",
                "minimum_out_amount" = EXCLUDED."minimum_out_amount",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(&self.pool_token_amount)
        .bind(&self.minimum_out_amount)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for RemoveLiquiditySingleSideRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM remove_liquidity_single_side_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for RemoveLiquiditySingleSideRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM remove_liquidity_single_side_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct RemoveLiquiditySingleSideMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for RemoveLiquiditySingleSideMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS remove_liquidity_single_side_instruction (
                -- Instruction data
                "pool_token_amount" NUMERIC(20) NOT NULL,
                "minimum_out_amount" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS remove_liquidity_single_side_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
