//! This code was AUTOGENERATED using the Codama library.
use {juniper::GraphQLObject, serde_json};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitializeTickArray")]
pub struct InitializeTickArrayGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub start_tick_index: i32,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::InitializeTickArrayRow> for InitializeTickArrayGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::InitializeTickArrayRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            start_tick_index: row.start_tick_index,
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
