//! This code was AUTOGENERATED using the Codama library.
/// Padding for future pool fields
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct Padding {
    /// Padding 0
    pub padding0: [u8; 6],
    /// Padding 1
    pub padding1: [u64; 21],
    /// Padding 2
    pub padding2: [u64; 21],
}
