//! This code was AUTOGENERATED using the Codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun Codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::U64;
use crate::accounts::Oracle;


#[derive(sqlx::FromRow, Debug, Clone)]
pub struct OracleRow {
    #[sqlx(flatten)]
        pub metadata: AccountRowMetadata,
            pub idx: U64,
        pub active_size: U64,
        pub length: U64,
}

impl OracleRow {
    pub fn from_parts(source: Oracle, metadata: AccountMetadata) -> Self {
        Self {
            metadata: metadata.into(),
                        idx: source.idx.into(),
                        active_size: source.active_size.into(),
                        length: source.length.into(),
                    }
    }
}

impl TryFrom<OracleRow> for Oracle {
    type Error = carbon_core::error::Error;
    fn try_from(source: OracleRow) -> Result<Self, Self::Error> {
        Ok(Self {
                        idx: *source.idx,
                        active_size: *source.active_size,
                        length: *source.length,
                    })
    }
}

impl carbon_core::postgres::operations::Table for Oracle {
    fn table() -> &'static str {
        "oracle_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
                        "__pubkey",
            "__slot",
                                    "idx",
                        "active_size",
                        "length",
                    ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for OracleRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO oracle_account (
                            "idx",
                            "active_size",
                            "length",
                                        __pubkey, __slot
                        ) VALUES (
                                                                            $1,                            $2,                            $3,                            $4,                            $5                    )"#)
                .bind(self.idx.clone())
                .bind(self.active_size.clone())
                .bind(self.length.clone())
                        .bind(self.metadata.pubkey.clone())
        .bind(self.metadata.slot.clone())
                .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for OracleRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO oracle_account (
                        "idx",
                        "active_size",
                        "length",
                                    __pubkey, __slot
                    ) VALUES (
                                                                        $1,                        $2,                        $3,                        $4,                        $5                    ) ON CONFLICT (
                        __pubkey
                    ) DO UPDATE SET
                        "idx" = EXCLUDED."idx",
                        "active_size" = EXCLUDED."active_size",
                        "length" = EXCLUDED."length",
                                    __slot = EXCLUDED.__slot
                    "#)
                .bind(self.idx.clone())
                .bind(self.active_size.clone())
                .bind(self.length.clone())
                        .bind(self.metadata.pubkey)
        .bind(self.metadata.slot.clone())
                .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for OracleRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM oracle_account WHERE
                        __pubkey = $1
                    "#)
                .bind(key)
                .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for OracleRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM oracle_account WHERE
                        __pubkey = $1
                    "#)
                .bind(key)
                .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))
        ?;

        Ok(row)
    }
}

pub struct OracleMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for OracleMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS oracle_account (
                        -- Account data
                                    "idx" NUMERIC(20) NOT NULL,
                        "active_size" NUMERIC(20) NOT NULL,
                        "length" NUMERIC(20) NOT NULL,
            
                        -- Account metadata
            __pubkey BYTEA NOT NULL,
            __slot NUMERIC(20),
            
                        PRIMARY KEY (__pubkey)
                    )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS oracle_account"#).execute(connection).await?;
        Ok(())
    }
}

