//! This code was AUTOGENERATED using the Codama library.
use {crate::types::graphql::PositionBinDataGraphQL, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DummyZcAccount")]
pub struct DummyZcAccountGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub position_bin_data: PositionBinDataGraphQL,
}

impl TryFrom<crate::accounts::postgres::DummyZcAccountRow> for DummyZcAccountGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::DummyZcAccountRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            position_bin_data: row.position_bin_data.0.into(),
        })
    }
}
