//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct DisableRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub disable_create_pool: bool,
    pub disable_deposit: bool,
    pub disable_withdraw: bool,
    pub disable_buy: bool,
    pub disable_sell: bool,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl DisableRow {
    pub fn from_parts(
        source: crate::instructions::disable::Disable,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            disable_create_pool: source.disable_create_pool,
            disable_deposit: source.disable_deposit,
            disable_withdraw: source.disable_withdraw,
            disable_buy: source.disable_buy,
            disable_sell: source.disable_sell,
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<DisableRow> for crate::instructions::disable::Disable {
    type Error = carbon_core::error::Error;
    fn try_from(source: DisableRow) -> Result<Self, Self::Error> {
        Ok(Self {
            disable_create_pool: source.disable_create_pool,
            disable_deposit: source.disable_deposit,
            disable_withdraw: source.disable_withdraw,
            disable_buy: source.disable_buy,
            disable_sell: source.disable_sell,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::disable::Disable {
    fn table() -> &'static str {
        "disable_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "disable_create_pool",
            "disable_deposit",
            "disable_withdraw",
            "disable_buy",
            "disable_sell",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for DisableRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO disable_instruction (
                "disable_create_pool",
                "disable_deposit",
                "disable_withdraw",
                "disable_buy",
                "disable_sell",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            )"#,
        )
        .bind(self.disable_create_pool)
        .bind(self.disable_deposit)
        .bind(self.disable_withdraw)
        .bind(self.disable_buy)
        .bind(self.disable_sell)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for DisableRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO disable_instruction (
                "disable_create_pool",
                "disable_deposit",
                "disable_withdraw",
                "disable_buy",
                "disable_sell",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "disable_create_pool" = EXCLUDED."disable_create_pool",
                "disable_deposit" = EXCLUDED."disable_deposit",
                "disable_withdraw" = EXCLUDED."disable_withdraw",
                "disable_buy" = EXCLUDED."disable_buy",
                "disable_sell" = EXCLUDED."disable_sell",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(self.disable_create_pool)
        .bind(self.disable_deposit)
        .bind(self.disable_withdraw)
        .bind(self.disable_buy)
        .bind(self.disable_sell)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for DisableRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM disable_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for DisableRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM disable_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct DisableMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for DisableMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS disable_instruction (
                -- Instruction data
                "disable_create_pool" BOOLEAN NOT NULL,
                "disable_deposit" BOOLEAN NOT NULL,
                "disable_withdraw" BOOLEAN NOT NULL,
                "disable_buy" BOOLEAN NOT NULL,
                "disable_sell" BOOLEAN NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS disable_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
