[package]
name = "carbon-pumpfun-decoder"
version = "0.12.0"
description = "Pumpfun Decoder"
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "decoder", "pumpfun"]
categories = ["encoding"]

[lib]
crate-type = ["rlib"]

[features]
default = []

serde = ["dep:serde", "carbon-borsh-types/serde"]

postgres = [
    "carbon-core/postgres",
    "dep:sqlx",
    "dep:async-trait",
    "dep:sqlx_migrator",
    "serde",
]

graphql = [
    "carbon-core/graphql",
    "dep:juniper",
    "dep:base64",
    "serde",
]

[dependencies]
carbon-core = { workspace = true, features = ["macros"], default-features = false }
carbon-borsh-types = { path = "../../crates/borsh-types" }
borsh = { version = "1.5.1", features = ["derive"] }
solana-pubkey = { version = "^3.0.0", features = ["borsh"] }
solana-account = "3.0.0"
solana-instruction = { version = "~3.0.0", default-features = false }
serde_json = "1.0.145"

serde = { version = "1.0.228", features = ["derive"], optional = true }
serde-big-array = { version = "0.5.1", optional = true }

sqlx = { version = "0.8.6", features = ["postgres", "rust_decimal"], optional = true }
async-trait = { version = "0.1.89", optional = true }
sqlx_migrator = { version = "0.17.0", optional = true }

juniper = { version = "0.16.2", optional = true }
base64 = { version = "0.22.1", optional = true }


[dev-dependencies]
carbon-test-utils = { workspace = true }
