//! This code was AUTOGENERATED using the Codama library.
use crate::types::RoutePlanStepV2;
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ExactOutRouteV2Row {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub out_amount: U64,
    pub quoted_in_amount: U64,
    pub slippage_bps: U16,
    pub platform_fee_bps: U16,
    pub positive_slippage_bps: U16,
    pub route_plan: sqlx::types::Json<Vec<RoutePlanStepV2>>,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl ExactOutRouteV2Row {
    pub fn from_parts(
        source: crate::instructions::exact_out_route_v2::ExactOutRouteV2,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            out_amount: source.out_amount.into(),
            quoted_in_amount: source.quoted_in_amount.into(),
            slippage_bps: source.slippage_bps.into(),
            platform_fee_bps: source.platform_fee_bps.into(),
            positive_slippage_bps: source.positive_slippage_bps.into(),
            route_plan: sqlx::types::Json(source.route_plan.to_vec()),
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<ExactOutRouteV2Row> for crate::instructions::exact_out_route_v2::ExactOutRouteV2 {
    type Error = carbon_core::error::Error;
    fn try_from(source: ExactOutRouteV2Row) -> Result<Self, Self::Error> {
        Ok(Self {
            out_amount: *source.out_amount,
            quoted_in_amount: *source.quoted_in_amount,
            slippage_bps: source.slippage_bps.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            platform_fee_bps: source.platform_fee_bps.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            positive_slippage_bps: source.positive_slippage_bps.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            route_plan: source.route_plan.0,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::exact_out_route_v2::ExactOutRouteV2
{
    fn table() -> &'static str {
        "exact_out_route_v2_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "out_amount",
            "quoted_in_amount",
            "slippage_bps",
            "platform_fee_bps",
            "positive_slippage_bps",
            "route_plan",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ExactOutRouteV2Row {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO exact_out_route_v2_instruction (
                "out_amount",
                "quoted_in_amount",
                "slippage_bps",
                "platform_fee_bps",
                "positive_slippage_bps",
                "route_plan",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
            )"#,
        )
        .bind(&self.out_amount)
        .bind(&self.quoted_in_amount)
        .bind(self.slippage_bps)
        .bind(self.platform_fee_bps)
        .bind(self.positive_slippage_bps)
        .bind(&self.route_plan)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ExactOutRouteV2Row {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO exact_out_route_v2_instruction (
                "out_amount",
                "quoted_in_amount",
                "slippage_bps",
                "platform_fee_bps",
                "positive_slippage_bps",
                "route_plan",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "out_amount" = EXCLUDED."out_amount",
                "quoted_in_amount" = EXCLUDED."quoted_in_amount",
                "slippage_bps" = EXCLUDED."slippage_bps",
                "platform_fee_bps" = EXCLUDED."platform_fee_bps",
                "positive_slippage_bps" = EXCLUDED."positive_slippage_bps",
                "route_plan" = EXCLUDED."route_plan",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(&self.out_amount)
        .bind(&self.quoted_in_amount)
        .bind(self.slippage_bps)
        .bind(self.platform_fee_bps)
        .bind(self.positive_slippage_bps)
        .bind(&self.route_plan)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ExactOutRouteV2Row {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM exact_out_route_v2_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for ExactOutRouteV2Row {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM exact_out_route_v2_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ExactOutRouteV2MigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ExactOutRouteV2MigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS exact_out_route_v2_instruction (
                -- Instruction data
                "out_amount" NUMERIC(20) NOT NULL,
                "quoted_in_amount" NUMERIC(20) NOT NULL,
                "slippage_bps" INT4 NOT NULL,
                "platform_fee_bps" INT4 NOT NULL,
                "positive_slippage_bps" INT4 NOT NULL,
                "route_plan" JSONB NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS exact_out_route_v2_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
