//! This code was AUTOGENERATED using the Codama library.
use crate::types::GroupEventHeader;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct MarginfiGroupCreateEvent {
    pub header: GroupEventHeader,
}
