//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::{RiskTier, WrappedI80F48},
    solana_pubkey::Pubkey,
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct StakedSettingsConfig {
    pub oracle: Pubkey,
    pub asset_weight_init: WrappedI80F48,
    pub asset_weight_maint: WrappedI80F48,
    pub deposit_limit: u64,
    pub total_asset_value_init_limit: u64,
    pub oracle_max_age: u16,
    /// WARN: You almost certainly want "Collateral", using Isolated risk tier
    /// makes the asset worthless as collateral, and is generally useful
    /// only when creating a staked collateral pool for rewards purposes
    /// only.
    pub risk_tier: RiskTier,
}
