//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::TransferOwnershipParams,
    carbon_core::{
        account_utils::next_account,
        deserialize::{ArrangeAccounts, CarbonDeserialize},
    },
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TransferOwnership {
    pub params: TransferOwnershipParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TransferOwnershipInstructionAccounts {
    pub owner: solana_pubkey::Pubkey,
    pub message_transmitter: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CarbonDeserialize for TransferOwnership {
    const DISCRIMINATOR: &'static [u8] = &[65, 177, 215, 73, 53, 45, 99, 47];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for TransferOwnership {
    type ArrangedAccounts = TransferOwnershipInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let owner = next_account(&mut iter)?;
        let message_transmitter = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(TransferOwnershipInstructionAccounts {
            owner,
            message_transmitter,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
