//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TokenLendingOrderBook {
    pub fee_authority: Pubkey,
    pub loan_mint: Pubkey,
    pub collateral_mint: Pubkey,
    pub collateral_token_program: Pubkey,
    pub duration: u64,
    pub min_liquidity: u64,
    pub max_liquidity: u64,
    pub apr: u32,
    pub fee_permillicentage: u16,
    pub collateral_decimals: u8,
    pub version: u8,
    pub bump: u8,
    pub padding: [u8; 7],
}

impl TokenLendingOrderBook {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [192, 71, 92, 163, 99, 85, 39, 27] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
