//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// migrate to cpmm, creator fee on quote token or both token
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "AmmCreatorFeeOn")]
pub enum AmmCreatorFeeOnGraphQL {
    QuoteToken,
    BothToken,
}

impl From<crate::types::AmmCreatorFeeOn> for AmmCreatorFeeOnGraphQL {
    fn from(original: crate::types::AmmCreatorFeeOn) -> Self {
        match original {
            crate::types::AmmCreatorFeeOn::QuoteToken => Self::QuoteToken,
            crate::types::AmmCreatorFeeOn::BothToken => Self::BothToken,
        }
    }
}
