//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::U64, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VestingSchedule")]
pub struct VestingScheduleGraphQL {
    pub total_locked_amount: U64,
    pub cliff_period: U64,
    pub unlock_period: U64,
    pub start_time: U64,
    pub allocated_share_amount: U64,
}

impl From<crate::types::VestingSchedule> for VestingScheduleGraphQL {
    fn from(original: crate::types::VestingSchedule) -> Self {
        Self {
            total_locked_amount: carbon_core::graphql::primitives::U64(
                original.total_locked_amount,
            ),
            cliff_period: carbon_core::graphql::primitives::U64(original.cliff_period),
            unlock_period: carbon_core::graphql::primitives::U64(original.unlock_period),
            start_time: carbon_core::graphql::primitives::U64(original.start_time),
            allocated_share_amount: carbon_core::graphql::primitives::U64(
                original.allocated_share_amount,
            ),
        }
    }
}
