//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account_utils::next_account,
    deserialize::{ArrangeAccounts, CarbonDeserialize},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct CreateDonationFeePda {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateDonationFeePdaInstructionAccounts {
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub fee_program_global: solana_pubkey::Pubkey,
    pub donation_fee_pda: solana_pubkey::Pubkey,
    pub config_id: solana_pubkey::Pubkey,
    pub base_mint: solana_pubkey::Pubkey,
    pub bonding_curve: solana_pubkey::Pubkey,
    pub pool: solana_pubkey::Pubkey,
    pub sharing_config: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CarbonDeserialize for CreateDonationFeePda {
    const DISCRIMINATOR: &'static [u8] = &[244, 139, 16, 88, 14, 255, 122, 26];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for CreateDonationFeePda {
    type ArrangedAccounts = CreateDonationFeePdaInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let fee_program_global = next_account(&mut iter)?;
        let donation_fee_pda = next_account(&mut iter)?;
        let config_id = next_account(&mut iter)?;
        let base_mint = next_account(&mut iter)?;
        let bonding_curve = next_account(&mut iter)?;
        let pool = next_account(&mut iter)?;
        let sharing_config = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CreateDonationFeePdaInstructionAccounts {
            event_authority,
            program,
            payer,
            system_program,
            fee_program_global,
            donation_fee_pda,
            config_id,
            base_mint,
            bonding_curve,
            pool,
            sharing_config,
            remaining: remaining.to_vec(),
        })
    }
}
