//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
/// Get Fees
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct GetFees {
    pub is_pump_pool: bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetFeesInstructionAccounts {
    pub fee_config: solana_pubkey::Pubkey,
    pub config_program_id: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl GetFees {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [231, 37, 126, 85, 207, 91, 63, 52] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for GetFees {
    type ArrangedAccounts = GetFeesInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let fee_config = next_account(&mut iter)?;
        let config_program_id = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(GetFeesInstructionAccounts {
            fee_config,
            config_program_id,
            remaining: remaining.to_vec(),
        })
    }
}
