//! This code was AUTOGENERATED using the Codama library.
use carbon_core::deserialize::{ArrangeAccounts, CarbonDeserialize};
/// Revoke Fee Sharing Authority
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RevokeFeeSharingAuthority {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RevokeFeeSharingAuthorityInstructionAccounts {}

impl CarbonDeserialize for RevokeFeeSharingAuthority {
    const DISCRIMINATOR: &'static [u8] = &[18, 233, 158, 39, 185, 207, 58, 104];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for RevokeFeeSharingAuthority {
    type ArrangedAccounts = RevokeFeeSharingAuthorityInstructionAccounts;

    fn arrange_accounts(
        _accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        Some(RevokeFeeSharingAuthorityInstructionAccounts {})
    }
}
