//! This code was AUTOGENERATED using the Codama library.
//!
//! <https://github.com/codama-idl/codama>
//!
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitializeTransferHook")]
pub struct InitializeTransferHookGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub transfer_hook_discriminator: U8,
    pub authority: Option<Pubkey>,
    pub program_id: Option<Pubkey>,
}

impl TryFrom<crate::instructions::postgres::InitializeTransferHookRow>
    for InitializeTransferHookGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::InitializeTransferHookRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            transfer_hook_discriminator: carbon_core::graphql::primitives::U8(
                (*row.transfer_hook_discriminator) as u8,
            ),
            authority: row
                .authority
                .map(|v| carbon_core::graphql::primitives::Pubkey(v.0)),
            program_id: row
                .program_id
                .map(|v| carbon_core::graphql::primitives::Pubkey(v.0)),
        })
    }
}
