//! This code was AUTOGENERATED using the Codama library.
//!
//! <https://github.com/codama-idl/codama>
//!
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateGroupPointer")]
pub struct UpdateGroupPointerGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub group_pointer_discriminator: U8,
    pub group_address: Option<Pubkey>,
}

impl TryFrom<crate::instructions::postgres::UpdateGroupPointerRow> for UpdateGroupPointerGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::UpdateGroupPointerRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            group_pointer_discriminator: carbon_core::graphql::primitives::U8(
                (*row.group_pointer_discriminator) as u8,
            ),
            group_address: row
                .group_address
                .map(|v| carbon_core::graphql::primitives::Pubkey(v.0)),
        })
    }
}
