//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::SwapEventV2GraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SwapsEvent")]
pub struct SwapsEventGraphQL {
    pub swap_events: Vec<SwapEventV2GraphQL>,
}

impl From<crate::types::SwapsEvent> for SwapsEventGraphQL {
    fn from(original: crate::types::SwapsEvent) -> Self {
        Self {
            swap_events: original
                .swap_events
                .into_iter()
                .map(|item| item.into())
                .collect(),
        }
    }
}
