//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::{Asset, Position},
    solana_pubkey::Pubkey,
};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct SpreadAccount {
    pub authority: Pubkey,
    pub nonce: u8,
    pub balance: u64,
    pub series_expiry: [u64; 5],
    pub series_expiry_padding: u64,
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub positions: [Position; 46],
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub positions_padding: [Position; 92],
    pub asset: Asset,
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub padding: [u8; 262],
}

impl SpreadAccount {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [57, 130, 252, 136, 167, 177, 47, 162] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
