[package]
name = "token-indexing-example"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
axum = { workspace = true }
carbon-core = { workspace = true }
carbon-gql-server = { workspace = true }
carbon-log-metrics = { workspace = true }
carbon-postgres-client = { workspace = true }
carbon-token-program-decoder = { workspace = true, features = ["postgres", "graphql"] }
carbon-yellowstone-grpc-datasource = { workspace = true }
juniper = { workspace = true }
juniper_axum = { workspace = true }
juniper_graphql_ws = { workspace = true }
solana-client = { workspace = true }
solana-pubkey = { workspace = true }
solana-transaction-status = { workspace = true }
spl-token = { workspace = true }

async-trait = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }
yellowstone-grpc-proto = { workspace = true }

[dependencies.rustls]
default-features = false
features = ["std", "aws_lc_rs"]
version = "0.23.0"
