//! This code was AUTOGENERATED using the Codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun Codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

/// Configure an account with the confidential extension to reject any
/// incoming non-confidential transfers.
///
/// This instruction can be used to configure a confidential extension
/// account to exclusively receive confidential payments.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct DisableNonConfidentialCredits {
    pub confidential_transfer_discriminator: u8,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DisableNonConfidentialCreditsInstructionAccounts {
    pub token: solana_pubkey::Pubkey,
    pub authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl DisableNonConfidentialCredits {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 2 {
            return None;
        }
        let discriminator = &data[0..1];
        if discriminator != [27] {
            return None;
        }
        let confidential_transfer_discriminator = data[1];
        if confidential_transfer_discriminator != 12 {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[1..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for DisableNonConfidentialCredits {
    type ArrangedAccounts = DisableNonConfidentialCreditsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let token = next_account(&mut iter)?;
        let authority = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(DisableNonConfidentialCreditsInstructionAccounts {
            token,
            authority,
            remaining: remaining.to_vec(),
        })
    }
}
