//! This code was AUTOGENERATED using the Codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun Codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use carbon_core::CarbonDeserialize;

/// Update the interest rate. Only supported for mints that include the
/// `InterestBearingConfig` extension.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct UpdateRateInterestBearingMint {
    pub interest_bearing_mint_discriminator: u8,
    /// The interest rate to update.
    pub rate: i16,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateRateInterestBearingMintInstructionAccounts {
    pub mint: solana_pubkey::Pubkey,
    pub rate_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl UpdateRateInterestBearingMint {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 2 {
            return None;
        }
        let discriminator = &data[0..1];
        if discriminator != [33] {
            return None;
        }
        let interest_bearing_mint_discriminator = data[1];
        if interest_bearing_mint_discriminator != 1 {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[1..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for UpdateRateInterestBearingMint {
    type ArrangedAccounts = UpdateRateInterestBearingMintInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let mint = next_account(&mut iter)?;
        let rate_authority = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(UpdateRateInterestBearingMintInstructionAccounts {
            mint,
            rate_authority,
            remaining: remaining.to_vec(),
        })
    }
}
