//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::PubkeyValueChangeGraphQL, carbon_core::graphql::primitives::Pubkey,
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ChangeAuthorityEvent")]
pub struct ChangeAuthorityEventGraphQL {
    pub state: Pubkey,
    pub admin_change: Option<PubkeyValueChangeGraphQL>,
    pub validator_manager_change: Option<PubkeyValueChangeGraphQL>,
    pub operational_sol_account_change: Option<PubkeyValueChangeGraphQL>,
    pub treasury_msol_account_change: Option<PubkeyValueChangeGraphQL>,
    pub pause_authority_change: Option<PubkeyValueChangeGraphQL>,
}

impl From<crate::types::ChangeAuthorityEvent> for ChangeAuthorityEventGraphQL {
    fn from(original: crate::types::ChangeAuthorityEvent) -> Self {
        Self {
            state: carbon_core::graphql::primitives::Pubkey(original.state),
            admin_change: original.admin_change.map(|v| v.into()),
            validator_manager_change: original.validator_manager_change.map(|v| v.into()),
            operational_sol_account_change: original
                .operational_sol_account_change
                .map(|v| v.into()),
            treasury_msol_account_change: original.treasury_msol_account_change.map(|v| v.into()),
            pause_authority_change: original.pause_authority_change.map(|v| v.into()),
        }
    }
}
