//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ScopeConfiguration {
    /// Pubkey of the scope price feed (disabled if `null` or `default`)
    pub price_feed: Pubkey,
    /// This is the scope_id price chain that results in a price for the token
    pub price_chain: [u16; 4],
    /// This is the scope_id price chain for the twap
    pub twap_chain: [u16; 4],
}
