//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account::AccountMetadata,
    postgres::{
        metadata::AccountRowMetadata,
        primitives::{Pubkey, U64, U8},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct LockedClmmPositionStateRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub bump: Vec<U8>,
    pub position_owner: Pubkey,
    pub pool_id: Pubkey,
    pub position_id: Pubkey,
    pub locked_nft_account: Pubkey,
    pub fee_nft_mint: Pubkey,
    pub recent_epoch: U64,
    pub padding: Vec<U64>,
}

impl LockedClmmPositionStateRow {
    pub fn from_parts(
        source: crate::accounts::locked_clmm_position_state::LockedClmmPositionState,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            bump: source
                .bump
                .into_iter()
                .map(|element| element.into())
                .collect(),
            position_owner: source.position_owner.into(),
            pool_id: source.pool_id.into(),
            position_id: source.position_id.into(),
            locked_nft_account: source.locked_nft_account.into(),
            fee_nft_mint: source.fee_nft_mint.into(),
            recent_epoch: source.recent_epoch.into(),
            padding: source
                .padding
                .into_iter()
                .map(|element| element.into())
                .collect(),
        }
    }
}

impl TryFrom<LockedClmmPositionStateRow>
    for crate::accounts::locked_clmm_position_state::LockedClmmPositionState
{
    type Error = carbon_core::error::Error;
    fn try_from(source: LockedClmmPositionStateRow) -> Result<Self, Self::Error> {
        Ok(Self {
            bump: source
                .bump
                .into_iter()
                .map(|element| {
                    element.try_into().map_err(|_| {
                        carbon_core::error::Error::Custom(
                            "Failed to convert value from postgres primitive".to_string(),
                        )
                    })
                })
                .collect::<Result<Vec<_>, carbon_core::error::Error>>()?
                .try_into()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert array element to primitive".to_string(),
                    )
                })?,
            position_owner: *source.position_owner,
            pool_id: *source.pool_id,
            position_id: *source.position_id,
            locked_nft_account: *source.locked_nft_account,
            fee_nft_mint: *source.fee_nft_mint,
            recent_epoch: *source.recent_epoch,
            padding: source
                .padding
                .into_iter()
                .map(|element| Ok(*element))
                .collect::<Result<Vec<_>, carbon_core::error::Error>>()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to collect array elements".to_string(),
                    )
                })?
                .try_into()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert array element to primitive".to_string(),
                    )
                })?,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::accounts::locked_clmm_position_state::LockedClmmPositionState
{
    fn table() -> &'static str {
        "locked_clmm_position_state_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "bump",
            "position_owner",
            "pool_id",
            "position_id",
            "locked_nft_account",
            "fee_nft_mint",
            "recent_epoch",
            "padding",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for LockedClmmPositionStateRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO locked_clmm_position_state_account (
                "bump",
                "position_owner",
                "pool_id",
                "position_id",
                "locked_nft_account",
                "fee_nft_mint",
                "recent_epoch",
                "padding",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            )"#,
        )
        .bind(&self.bump)
        .bind(self.position_owner)
        .bind(self.pool_id)
        .bind(self.position_id)
        .bind(self.locked_nft_account)
        .bind(self.fee_nft_mint)
        .bind(&self.recent_epoch)
        .bind(&self.padding)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for LockedClmmPositionStateRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO locked_clmm_position_state_account (
                "bump",
                "position_owner",
                "pool_id",
                "position_id",
                "locked_nft_account",
                "fee_nft_mint",
                "recent_epoch",
                "padding",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "bump" = EXCLUDED."bump",
                "position_owner" = EXCLUDED."position_owner",
                "pool_id" = EXCLUDED."pool_id",
                "position_id" = EXCLUDED."position_id",
                "locked_nft_account" = EXCLUDED."locked_nft_account",
                "fee_nft_mint" = EXCLUDED."fee_nft_mint",
                "recent_epoch" = EXCLUDED."recent_epoch",
                "padding" = EXCLUDED."padding",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(&self.bump)
        .bind(self.position_owner)
        .bind(self.pool_id)
        .bind(self.position_id)
        .bind(self.locked_nft_account)
        .bind(self.fee_nft_mint)
        .bind(&self.recent_epoch)
        .bind(&self.padding)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for LockedClmmPositionStateRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM locked_clmm_position_state_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for LockedClmmPositionStateRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM locked_clmm_position_state_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct LockedClmmPositionStateMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for LockedClmmPositionStateMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS locked_clmm_position_state_account (
                -- Account data
                "bump" INT2[] NOT NULL,
                "position_owner" BYTEA NOT NULL,
                "pool_id" BYTEA NOT NULL,
                "position_id" BYTEA NOT NULL,
                "locked_nft_account" BYTEA NOT NULL,
                "fee_nft_mint" BYTEA NOT NULL,
                "recent_epoch" NUMERIC(20) NOT NULL,
                "padding" NUMERIC(20)[] NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS locked_clmm_position_state_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
