//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::deserialize::CarbonDeserialize, solana_pubkey::Pubkey};

/// Global program config account.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AmmConfig {
    pub pnl_owner: Pubkey,
    pub cancel_owner: Pubkey,
    pub pending1: [u64; 28],
    pub pending2: [u64; 31],
    pub create_pool_fee: u64,
}

impl CarbonDeserialize for AmmConfig {
    const DISCRIMINATOR: &'static [u8] = &[];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() != 544 {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[0..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
