//! This code was AUTOGENERATED using the Codama library.
use crate::PumpSwapDecoder;
use crate::PROGRAM_ID;

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod admin_set_coin_creator;
pub mod admin_update_token_incentives;
pub mod buy;
pub mod buy_exact_quote_in;
pub mod claim_cashback;
pub mod claim_token_incentives;
pub mod close_user_volume_accumulator;
pub mod collect_coin_creator_fee;
pub mod cpi_event;
pub mod create_config;
pub mod create_pool;
pub mod deposit;
pub mod disable;
pub mod extend_account;
pub mod init_user_volume_accumulator;
pub mod migrate_pool_coin_creator;
pub mod sell;
pub mod set_coin_creator;
pub mod set_reserved_fee_recipients;
pub mod sync_user_volume_accumulator;
pub mod toggle_cashback_enabled;
pub mod toggle_mayhem_mode;
pub mod transfer_creator_fees_to_pump;
pub mod update_admin;
pub mod update_fee_config;
pub mod withdraw;

pub use self::admin_set_coin_creator::*;
pub use self::admin_update_token_incentives::*;
pub use self::buy::*;
pub use self::buy_exact_quote_in::*;
pub use self::claim_cashback::*;
pub use self::claim_token_incentives::*;
pub use self::close_user_volume_accumulator::*;
pub use self::collect_coin_creator_fee::*;
pub use self::cpi_event::*;
pub use self::create_config::*;
pub use self::create_pool::*;
pub use self::deposit::*;
pub use self::disable::*;
pub use self::extend_account::*;
pub use self::init_user_volume_accumulator::*;
pub use self::migrate_pool_coin_creator::*;
pub use self::sell::*;
pub use self::set_coin_creator::*;
pub use self::set_reserved_fee_recipients::*;
pub use self::sync_user_volume_accumulator::*;
pub use self::toggle_cashback_enabled::*;
pub use self::toggle_mayhem_mode::*;
pub use self::transfer_creator_fees_to_pump::*;
pub use self::update_admin::*;
pub use self::update_fee_config::*;
pub use self::withdraw::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpSwapInstruction {
    AdminSetCoinCreator(AdminSetCoinCreator),
    AdminUpdateTokenIncentives(AdminUpdateTokenIncentives),
    Buy(Buy),
    BuyExactQuoteIn(BuyExactQuoteIn),
    ClaimCashback(ClaimCashback),
    ClaimTokenIncentives(ClaimTokenIncentives),
    CloseUserVolumeAccumulator(CloseUserVolumeAccumulator),
    CollectCoinCreatorFee(CollectCoinCreatorFee),
    CreateConfig(CreateConfig),
    CreatePool(CreatePool),
    Deposit(Deposit),
    Disable(Disable),
    ExtendAccount(ExtendAccount),
    InitUserVolumeAccumulator(InitUserVolumeAccumulator),
    MigratePoolCoinCreator(MigratePoolCoinCreator),
    Sell(Sell),
    SetCoinCreator(SetCoinCreator),
    SetReservedFeeRecipients(SetReservedFeeRecipients),
    SyncUserVolumeAccumulator(SyncUserVolumeAccumulator),
    ToggleCashbackEnabled(ToggleCashbackEnabled),
    ToggleMayhemMode(ToggleMayhemMode),
    TransferCreatorFeesToPump(TransferCreatorFeesToPump),
    UpdateAdmin(UpdateAdmin),
    UpdateFeeConfig(UpdateFeeConfig),
    Withdraw(Withdraw),
    // Anchor CPI Event Instruction
    CpiEvent(Box<CpiEvent>),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PumpSwapDecoder {
    type InstructionType = PumpSwapInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = admin_set_coin_creator::AdminSetCoinCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::AdminSetCoinCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                admin_update_token_incentives::AdminUpdateTokenIncentives::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::AdminUpdateTokenIncentives(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy::Buy::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::Buy(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy_exact_quote_in::BuyExactQuoteIn::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::BuyExactQuoteIn(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_cashback::ClaimCashback::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::ClaimCashback(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_token_incentives::ClaimTokenIncentives::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::ClaimTokenIncentives(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                close_user_volume_accumulator::CloseUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::CloseUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = collect_coin_creator_fee::CollectCoinCreatorFee::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::CollectCoinCreatorFee(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_config::CreateConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::CreateConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_pool::CreatePool::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::CreatePool(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = deposit::Deposit::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::Deposit(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = disable::Disable::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::Disable(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = extend_account::ExtendAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::ExtendAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                init_user_volume_accumulator::InitUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::InitUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = migrate_pool_coin_creator::MigratePoolCoinCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::MigratePoolCoinCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = sell::Sell::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::Sell(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_coin_creator::SetCoinCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::SetCoinCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                set_reserved_fee_recipients::SetReservedFeeRecipients::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::SetReservedFeeRecipients(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                sync_user_volume_accumulator::SyncUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::SyncUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_cashback_enabled::ToggleCashbackEnabled::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::ToggleCashbackEnabled(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_mayhem_mode::ToggleMayhemMode::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::ToggleMayhemMode(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                transfer_creator_fees_to_pump::TransferCreatorFeesToPump::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::TransferCreatorFeesToPump(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_admin::UpdateAdmin::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::UpdateAdmin(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_fee_config::UpdateFeeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::UpdateFeeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw::Withdraw::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::Withdraw(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpSwapInstruction::CpiEvent(Box::new(decoded)),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
