//! This code was AUTOGENERATED using the Codama library.
use crate::types::{
    PriceHeuristic, PythConfiguration, ScopeConfiguration, SwitchboardConfiguration,
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TokenInfo {
    /// UTF-8 encoded name of the token (null-terminated)
    pub name: [u8; 32],
    /// Heuristics limits of acceptable price
    pub heuristic: PriceHeuristic,
    /// Max divergence between twap and price in bps
    pub max_twap_divergence_bps: u64,
    pub max_age_price_seconds: u64,
    pub max_age_twap_seconds: u64,
    /// Scope price configuration
    pub scope_configuration: ScopeConfiguration,
    /// Switchboard configuration
    pub switchboard_configuration: SwitchboardConfiguration,
    /// Pyth configuration
    pub pyth_configuration: PythConfiguration,
    pub block_price_usage: u8,
    pub reserved: [u8; 7],
    pub padding: [u64; 19],
}
