//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GlobalConfig")]
pub struct GlobalConfigGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub emergency_mode: U8,
    pub flash_take_order_blocked: U8,
    pub new_orders_blocked: U8,
    pub orders_taking_blocked: U8,
    pub host_fee_bps: i32,
    pub padding0: Vec<U8>,
    pub order_close_delay_seconds: U64,
    pub padding1: Vec<U64>,
    pub pda_authority_previous_lamports_balance: U64,
    pub total_tip_amount: U64,
    pub host_tip_amount: U64,
    pub pda_authority: Pubkey,
    pub pda_authority_bump: U64,
    pub admin_authority: Pubkey,
    pub admin_authority_cached: Pubkey,
    pub txn_fee_cost: U64,
    pub ata_creation_cost: U64,
    pub padding2: Vec<U64>,
}

impl TryFrom<crate::accounts::postgres::GlobalConfigRow> for GlobalConfigGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::GlobalConfigRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            emergency_mode: carbon_core::graphql::primitives::U8((*row.emergency_mode) as u8),
            flash_take_order_blocked: carbon_core::graphql::primitives::U8(
                (*row.flash_take_order_blocked) as u8,
            ),
            new_orders_blocked: carbon_core::graphql::primitives::U8(
                (*row.new_orders_blocked) as u8,
            ),
            orders_taking_blocked: carbon_core::graphql::primitives::U8(
                (*row.orders_taking_blocked) as u8,
            ),
            host_fee_bps: *row.host_fee_bps,
            padding0: row
                .padding0
                .into_iter()
                .map(|x| carbon_core::graphql::primitives::U8((*x) as u8))
                .collect(),
            order_close_delay_seconds: carbon_core::graphql::primitives::U64(
                *row.order_close_delay_seconds,
            ),
            padding1: row
                .padding1
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U64(*item))
                .collect(),
            pda_authority_previous_lamports_balance: carbon_core::graphql::primitives::U64(
                *row.pda_authority_previous_lamports_balance,
            ),
            total_tip_amount: carbon_core::graphql::primitives::U64(*row.total_tip_amount),
            host_tip_amount: carbon_core::graphql::primitives::U64(*row.host_tip_amount),
            pda_authority: carbon_core::graphql::primitives::Pubkey(row.pda_authority.0),
            pda_authority_bump: carbon_core::graphql::primitives::U64(*row.pda_authority_bump),
            admin_authority: carbon_core::graphql::primitives::Pubkey(row.admin_authority.0),
            admin_authority_cached: carbon_core::graphql::primitives::Pubkey(
                row.admin_authority_cached.0,
            ),
            txn_fee_cost: carbon_core::graphql::primitives::U64(*row.txn_fee_cost),
            ata_creation_cost: carbon_core::graphql::primitives::U64(*row.ata_creation_cost),
            padding2: row
                .padding2
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U64(*item))
                .collect(),
        })
    }
}
