//! This code was AUTOGENERATED using the Codama library.
pub mod add_rewards_row;
pub mod deposit_to_farm_vault_row;
pub mod harvest_reward_row;
pub mod idl_missing_types_row;
pub mod initialize_farm_delegated_row;
pub mod initialize_farm_row;
pub mod initialize_global_config_row;
pub mod initialize_reward_row;
pub mod initialize_user_row;
pub mod refresh_farm_row;
pub mod refresh_user_state_row;
pub mod reward_user_once_row;
pub mod set_stake_delegated_row;
pub mod stake_row;
pub mod transfer_ownership_row;
pub mod unstake_row;
pub mod update_farm_admin_row;
pub mod update_farm_config_row;
pub mod update_global_config_admin_row;
pub mod update_global_config_row;
pub mod update_second_delegated_authority_row;
pub mod withdraw_from_farm_vault_row;
pub mod withdraw_reward_row;
pub mod withdraw_slashed_amount_row;
pub mod withdraw_treasury_row;
pub mod withdraw_unstaked_deposits_row;

pub use self::{
    add_rewards_row::*, deposit_to_farm_vault_row::*, harvest_reward_row::*,
    idl_missing_types_row::*, initialize_farm_delegated_row::*, initialize_farm_row::*,
    initialize_global_config_row::*, initialize_reward_row::*, initialize_user_row::*,
    refresh_farm_row::*, refresh_user_state_row::*, reward_user_once_row::*,
    set_stake_delegated_row::*, stake_row::*, transfer_ownership_row::*, unstake_row::*,
    update_farm_admin_row::*, update_farm_config_row::*, update_global_config_admin_row::*,
    update_global_config_row::*, update_second_delegated_authority_row::*,
    withdraw_from_farm_vault_row::*, withdraw_reward_row::*, withdraw_slashed_amount_row::*,
    withdraw_treasury_row::*, withdraw_unstaked_deposits_row::*,
};
use super::KaminoFarmsInstruction;

pub struct KaminoFarmsInstructionsMigration;

impl carbon_core::clickhouse::Migration for KaminoFarmsInstructionsMigration {
    fn app(&self) -> &str {
        "kamino-farms"
    }

    fn name(&self) -> &str {
        "kamino_farms_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::Operation>> {
        vec![
            Box::new(AddRewardsRowMigrationOperation),
            Box::new(DepositToFarmVaultRowMigrationOperation),
            Box::new(HarvestRewardRowMigrationOperation),
            Box::new(IdlMissingTypesRowMigrationOperation),
            Box::new(InitializeFarmRowMigrationOperation),
            Box::new(InitializeFarmDelegatedRowMigrationOperation),
            Box::new(InitializeGlobalConfigRowMigrationOperation),
            Box::new(InitializeRewardRowMigrationOperation),
            Box::new(InitializeUserRowMigrationOperation),
            Box::new(RefreshFarmRowMigrationOperation),
            Box::new(RefreshUserStateRowMigrationOperation),
            Box::new(RewardUserOnceRowMigrationOperation),
            Box::new(SetStakeDelegatedRowMigrationOperation),
            Box::new(StakeRowMigrationOperation),
            Box::new(TransferOwnershipRowMigrationOperation),
            Box::new(UnstakeRowMigrationOperation),
            Box::new(UpdateFarmAdminRowMigrationOperation),
            Box::new(UpdateFarmConfigRowMigrationOperation),
            Box::new(UpdateGlobalConfigRowMigrationOperation),
            Box::new(UpdateGlobalConfigAdminRowMigrationOperation),
            Box::new(UpdateSecondDelegatedAuthorityRowMigrationOperation),
            Box::new(WithdrawFromFarmVaultRowMigrationOperation),
            Box::new(WithdrawRewardRowMigrationOperation),
            Box::new(WithdrawSlashedAmountRowMigrationOperation),
            Box::new(WithdrawTreasuryRowMigrationOperation),
            Box::new(WithdrawUnstakedDepositsRowMigrationOperation),
        ]
    }
}

pub enum KaminoFarmsInstructionRow {
    AddRewards(AddRewardsRow),
    DepositToFarmVault(DepositToFarmVaultRow),
    HarvestReward(HarvestRewardRow),
    IdlMissingTypes(IdlMissingTypesRow),
    InitializeFarm(InitializeFarmRow),
    InitializeFarmDelegated(InitializeFarmDelegatedRow),
    InitializeGlobalConfig(InitializeGlobalConfigRow),
    InitializeReward(InitializeRewardRow),
    InitializeUser(InitializeUserRow),
    RefreshFarm(RefreshFarmRow),
    RefreshUserState(RefreshUserStateRow),
    RewardUserOnce(RewardUserOnceRow),
    SetStakeDelegated(SetStakeDelegatedRow),
    Stake(StakeRow),
    TransferOwnership(TransferOwnershipRow),
    Unstake(UnstakeRow),
    UpdateFarmAdmin(UpdateFarmAdminRow),
    UpdateFarmConfig(UpdateFarmConfigRow),
    UpdateGlobalConfig(UpdateGlobalConfigRow),
    UpdateGlobalConfigAdmin(UpdateGlobalConfigAdminRow),
    UpdateSecondDelegatedAuthority(UpdateSecondDelegatedAuthorityRow),
    WithdrawFromFarmVault(WithdrawFromFarmVaultRow),
    WithdrawReward(WithdrawRewardRow),
    WithdrawSlashedAmount(WithdrawSlashedAmountRow),
    WithdrawTreasury(WithdrawTreasuryRow),
    WithdrawUnstakedDeposits(WithdrawUnstakedDepositsRow),
}

pub struct KaminoFarmsInstructionMetadata<'a>(
    pub &'a carbon_core::instruction::InstructionMetadata,
    pub &'a KaminoFarmsInstruction,
);

impl<'a> carbon_core::clickhouse::BatchInsert for KaminoFarmsInstructionMetadata<'a> {
    type Row = KaminoFarmsInstructionRow;

    fn batch_insert(&self, rows: &mut Vec<Self::Row>) -> carbon_core::error::CarbonResult<()> {
        let &Self(metadata, instruction) = self;

        macro_rules! insert_branch {
            ($variant:ident, $row:ty) => {
                if let KaminoFarmsInstruction::$variant { data, accounts, .. } = instruction {
                    rows.push(KaminoFarmsInstructionRow::$variant(<$row>::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?));
                    return Ok(());
                }
            };
        }

        insert_branch!(AddRewards, AddRewardsRow);
        insert_branch!(DepositToFarmVault, DepositToFarmVaultRow);
        insert_branch!(HarvestReward, HarvestRewardRow);
        insert_branch!(IdlMissingTypes, IdlMissingTypesRow);
        insert_branch!(InitializeFarm, InitializeFarmRow);
        insert_branch!(InitializeFarmDelegated, InitializeFarmDelegatedRow);
        insert_branch!(InitializeGlobalConfig, InitializeGlobalConfigRow);
        insert_branch!(InitializeReward, InitializeRewardRow);
        insert_branch!(InitializeUser, InitializeUserRow);
        insert_branch!(RefreshFarm, RefreshFarmRow);
        insert_branch!(RefreshUserState, RefreshUserStateRow);
        insert_branch!(RewardUserOnce, RewardUserOnceRow);
        insert_branch!(SetStakeDelegated, SetStakeDelegatedRow);
        insert_branch!(Stake, StakeRow);
        insert_branch!(TransferOwnership, TransferOwnershipRow);
        insert_branch!(Unstake, UnstakeRow);
        insert_branch!(UpdateFarmAdmin, UpdateFarmAdminRow);
        insert_branch!(UpdateFarmConfig, UpdateFarmConfigRow);
        insert_branch!(UpdateGlobalConfig, UpdateGlobalConfigRow);
        insert_branch!(UpdateGlobalConfigAdmin, UpdateGlobalConfigAdminRow);
        insert_branch!(
            UpdateSecondDelegatedAuthority,
            UpdateSecondDelegatedAuthorityRow
        );
        insert_branch!(WithdrawFromFarmVault, WithdrawFromFarmVaultRow);
        insert_branch!(WithdrawReward, WithdrawRewardRow);
        insert_branch!(WithdrawSlashedAmount, WithdrawSlashedAmountRow);
        insert_branch!(WithdrawTreasury, WithdrawTreasuryRow);
        insert_branch!(WithdrawUnstakedDeposits, WithdrawUnstakedDepositsRow);

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for KaminoFarmsInstructionRow {
    async fn batch_commit(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {{
                let branch_rows: Vec<$row> = rows
                    .iter()
                    .filter_map(|row| match row {
                        Self::$variant(row) => Some(row.clone()),
                        _ => None,
                    })
                    .collect();

                if !branch_rows.is_empty() {
                    <$row as carbon_core::clickhouse::Insert>::insert(client, &branch_rows).await?;
                }
            }};
        }

        commit_branch!(AddRewards, AddRewardsRow);
        commit_branch!(DepositToFarmVault, DepositToFarmVaultRow);
        commit_branch!(HarvestReward, HarvestRewardRow);
        commit_branch!(IdlMissingTypes, IdlMissingTypesRow);
        commit_branch!(InitializeFarm, InitializeFarmRow);
        commit_branch!(InitializeFarmDelegated, InitializeFarmDelegatedRow);
        commit_branch!(InitializeGlobalConfig, InitializeGlobalConfigRow);
        commit_branch!(InitializeReward, InitializeRewardRow);
        commit_branch!(InitializeUser, InitializeUserRow);
        commit_branch!(RefreshFarm, RefreshFarmRow);
        commit_branch!(RefreshUserState, RefreshUserStateRow);
        commit_branch!(RewardUserOnce, RewardUserOnceRow);
        commit_branch!(SetStakeDelegated, SetStakeDelegatedRow);
        commit_branch!(Stake, StakeRow);
        commit_branch!(TransferOwnership, TransferOwnershipRow);
        commit_branch!(Unstake, UnstakeRow);
        commit_branch!(UpdateFarmAdmin, UpdateFarmAdminRow);
        commit_branch!(UpdateFarmConfig, UpdateFarmConfigRow);
        commit_branch!(UpdateGlobalConfig, UpdateGlobalConfigRow);
        commit_branch!(UpdateGlobalConfigAdmin, UpdateGlobalConfigAdminRow);
        commit_branch!(
            UpdateSecondDelegatedAuthority,
            UpdateSecondDelegatedAuthorityRow
        );
        commit_branch!(WithdrawFromFarmVault, WithdrawFromFarmVaultRow);
        commit_branch!(WithdrawReward, WithdrawRewardRow);
        commit_branch!(WithdrawSlashedAmount, WithdrawSlashedAmountRow);
        commit_branch!(WithdrawTreasury, WithdrawTreasuryRow);
        commit_branch!(WithdrawUnstakedDeposits, WithdrawUnstakedDepositsRow);

        Ok(())
    }
}
