//! This code was AUTOGENERATED using the Codama library.
pub mod pool_row;
pub mod strategy_row;
pub mod vault_row;

pub use self::{pool_row::*, strategy_row::*, vault_row::*};
use super::StabbleStableSwapAccount;

pub struct StabbleStableSwapAccountsMigration;

impl carbon_core::clickhouse::Migration for StabbleStableSwapAccountsMigration {
    fn app(&self) -> &str {
        "stabble-stable-swap"
    }

    fn name(&self) -> &str {
        "stabble_stable_swap_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::Operation>> {
        vec![
            Box::new(PoolRowMigrationOperation),
            Box::new(StrategyRowMigrationOperation),
            Box::new(VaultRowMigrationOperation),
        ]
    }
}

pub enum StabbleStableSwapAccountRow {
    Pool(PoolRow),
    Strategy(StrategyRow),
    Vault(VaultRow),
}

pub struct StabbleStableSwapAccountMetadata<'a>(
    pub &'a carbon_core::account::AccountMetadata,
    pub &'a StabbleStableSwapAccount,
);

impl<'a> carbon_core::clickhouse::BatchInsert for StabbleStableSwapAccountMetadata<'a> {
    type Row = StabbleStableSwapAccountRow;

    fn batch_insert(&self, rows: &mut Vec<Self::Row>) -> carbon_core::error::CarbonResult<()> {
        let &Self(metadata, account) = self;

        macro_rules! insert_branch {
            ($variant:ident, $row:ty, boxed) => {
                if let StabbleStableSwapAccount::$variant(account) = account {
                    rows.push(StabbleStableSwapAccountRow::$variant(<$row>::try_from((
                        account.as_ref().clone(),
                        metadata.clone(),
                    ))?));
                    return Ok(());
                }
            };
            ($variant:ident, $row:ty, plain) => {
                if let StabbleStableSwapAccount::$variant(account) = account {
                    rows.push(StabbleStableSwapAccountRow::$variant(<$row>::try_from((
                        account.clone(),
                        metadata.clone(),
                    ))?));
                    return Ok(());
                }
            };
        }

        insert_branch!(Pool, PoolRow, boxed);
        insert_branch!(Strategy, StrategyRow, boxed);
        insert_branch!(Vault, VaultRow, boxed);

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for StabbleStableSwapAccountRow {
    async fn batch_commit(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {{
                let branch_rows: Vec<$row> = rows
                    .iter()
                    .filter_map(|row| match row {
                        Self::$variant(row) => Some(row.clone()),
                        _ => None,
                    })
                    .collect();

                if !branch_rows.is_empty() {
                    <$row as carbon_core::clickhouse::Insert>::insert(client, &branch_rows).await?;
                }
            }};
        }

        commit_branch!(Pool, PoolRow);
        commit_branch!(Strategy, StrategyRow);
        commit_branch!(Vault, VaultRow);

        Ok(())
    }
}
