//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::HandleReceiveMessageParams,
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct HandleReceiveFinalizedMessage {
    pub params: HandleReceiveMessageParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct HandleReceiveFinalizedMessageInstructionAccounts {
    pub authority_pda: solana_pubkey::Pubkey,
    pub token_messenger: solana_pubkey::Pubkey,
    pub remote_token_messenger: solana_pubkey::Pubkey,
    pub token_minter: solana_pubkey::Pubkey,
    pub local_token: solana_pubkey::Pubkey,
    pub token_pair: solana_pubkey::Pubkey,
    pub fee_recipient_token_account: solana_pubkey::Pubkey,
    pub recipient_token_account: solana_pubkey::Pubkey,
    pub custody_token_account: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl HandleReceiveFinalizedMessage {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [186, 252, 239, 70, 86, 180, 110, 95] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for HandleReceiveFinalizedMessage {
    type ArrangedAccounts = HandleReceiveFinalizedMessageInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let authority_pda = next_account(&mut iter)?;
        let token_messenger = next_account(&mut iter)?;
        let remote_token_messenger = next_account(&mut iter)?;
        let token_minter = next_account(&mut iter)?;
        let local_token = next_account(&mut iter)?;
        let token_pair = next_account(&mut iter)?;
        let fee_recipient_token_account = next_account(&mut iter)?;
        let recipient_token_account = next_account(&mut iter)?;
        let custody_token_account = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(HandleReceiveFinalizedMessageInstructionAccounts {
            authority_pda,
            token_messenger,
            remote_token_messenger,
            token_minter,
            local_token,
            token_pair,
            fee_recipient_token_account,
            recipient_token_account,
            custody_token_account,
            token_program,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
