//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::RoutePlanStepGraphQL;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
use serde_json;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SharedAccountsRoute")]
pub struct SharedAccountsRouteGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub id: U8,
    pub route_plan: Vec<RoutePlanStepGraphQL>,
    pub in_amount: U64,
    pub quoted_out_amount: U64,
    pub slippage_bps: i32,
    pub platform_fee_bps: U8,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::SharedAccountsRouteRow> for SharedAccountsRouteGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::SharedAccountsRouteRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            id: carbon_core::graphql::primitives::U8((*row.id) as u8),
            route_plan: row
                .route_plan
                .0
                .into_iter()
                .map(|item| item.into())
                .collect(),
            in_amount: carbon_core::graphql::primitives::U64(*row.in_amount),
            quoted_out_amount: carbon_core::graphql::primitives::U64(*row.quoted_out_amount),
            slippage_bps: *row.slippage_bps,
            platform_fee_bps: carbon_core::graphql::primitives::U8((*row.platform_fee_bps) as u8),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
