//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct CreateOrderEvent {
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub order_key: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub maker: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub input_mint: Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub output_mint: Pubkey,
    pub in_amount: u64,
    pub out_amount: u64,
    pub expired_at: Option<i64>,
}
