//! This code was AUTOGENERATED using the Codama library.
use {crate::types::graphql::DummyParamsGraphQL, juniper::GraphQLObject, serde_json};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DummyIx")]
pub struct DummyIxGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub ixs: DummyParamsGraphQL,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::DummyIxRow> for DummyIxGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::DummyIxRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            ixs: row.ixs.0.into(),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
