//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account_utils::next_account,
    deserialize::{ArrangeAccounts, CarbonDeserialize},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ChangeSwapFeePrivileged {
    pub new_swap_fee: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ChangeSwapFeePrivilegedInstructionAccounts {
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub pool: solana_pubkey::Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub vault: solana_pubkey::Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub admin: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CarbonDeserialize for ChangeSwapFeePrivileged {
    const DISCRIMINATOR: &'static [u8] = &[155, 200, 14, 91, 105, 38, 220, 119];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for ChangeSwapFeePrivileged {
    type ArrangedAccounts = ChangeSwapFeePrivilegedInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let pool = next_account(&mut iter)?;
        let vault = next_account(&mut iter)?;
        let admin = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ChangeSwapFeePrivilegedInstructionAccounts {
            pool,
            vault,
            admin,
            remaining: remaining.to_vec(),
        })
    }
}
