//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct ZapDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("RH1S6CRJzZNDsrhYKPUcehvvtdGSzKr5DHKsnz12pVA");

pub mod accounts;
pub mod events;
pub mod instructions;
pub mod types;
