//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::AnchorDecimalGraphQL,
    carbon_core::graphql::primitives::{I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "PricingParameters")]
pub struct PricingParametersGraphQL {
    pub option_trade_normalizer: AnchorDecimalGraphQL,
    pub future_trade_normalizer: AnchorDecimalGraphQL,
    pub max_volatility_retreat: AnchorDecimalGraphQL,
    pub max_interest_retreat: AnchorDecimalGraphQL,
    pub max_delta: U64,
    pub min_delta: U64,
    pub min_volatility: U64,
    pub max_volatility: U64,
    pub min_interest_rate: I64,
    pub max_interest_rate: I64,
}

impl From<crate::types::PricingParameters> for PricingParametersGraphQL {
    fn from(original: crate::types::PricingParameters) -> Self {
        Self {
            option_trade_normalizer: original.option_trade_normalizer.into(),
            future_trade_normalizer: original.future_trade_normalizer.into(),
            max_volatility_retreat: original.max_volatility_retreat.into(),
            max_interest_retreat: original.max_interest_retreat.into(),
            max_delta: carbon_core::graphql::primitives::U64(original.max_delta),
            min_delta: carbon_core::graphql::primitives::U64(original.min_delta),
            min_volatility: carbon_core::graphql::primitives::U64(original.min_volatility),
            max_volatility: carbon_core::graphql::primitives::U64(original.max_volatility),
            min_interest_rate: carbon_core::graphql::primitives::I64(original.min_interest_rate),
            max_interest_rate: carbon_core::graphql::primitives::I64(original.max_interest_rate),
        }
    }
}
