//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "OverrideCurveParam")]
pub struct OverrideCurveParamGraphQL {
    pub new_amp: U64,
    pub updated_timestamp: U64,
    pub pool: Pubkey,
}

impl From<crate::types::OverrideCurveParam> for OverrideCurveParamGraphQL {
    fn from(original: crate::types::OverrideCurveParam) -> Self {
        Self {
            new_amp: carbon_core::graphql::primitives::U64(original.new_amp),
            updated_timestamp: carbon_core::graphql::primitives::U64(original.updated_timestamp),
            pool: carbon_core::graphql::primitives::Pubkey(original.pool),
        }
    }
}
