//! This code was AUTOGENERATED using the Codama library.
pub mod admin_cancel_orders_row;
pub mod create_config_account_row;
pub mod deposit_row;
pub mod initialize2_row;
pub mod initialize_row;
pub mod migrate_to_open_book_row;
pub mod monitor_step_row;
pub mod pre_initialize_row;
pub mod set_params_row;
pub mod simulate_info_row;
pub mod swap_base_in_row;
pub mod swap_base_out_row;
pub mod update_config_account_row;
pub mod withdraw_pnl_row;
pub mod withdraw_row;
pub mod withdraw_srm_row;

pub use self::{
    admin_cancel_orders_row::*, create_config_account_row::*, deposit_row::*, initialize2_row::*,
    initialize_row::*, migrate_to_open_book_row::*, monitor_step_row::*, pre_initialize_row::*,
    set_params_row::*, simulate_info_row::*, swap_base_in_row::*, swap_base_out_row::*,
    update_config_account_row::*, withdraw_pnl_row::*, withdraw_row::*, withdraw_srm_row::*,
};
use super::RaydiumAmmV4Instruction;

pub struct RaydiumAmmV4InstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for RaydiumAmmV4InstructionsMigration {
    fn app(&self) -> &str {
        "raydium-amm-v4"
    }

    fn name(&self) -> &str {
        "raydium_amm_v4_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AdminCancelOrdersMigrationOperation),
            Box::new(CreateConfigAccountMigrationOperation),
            Box::new(DepositMigrationOperation),
            Box::new(InitializeMigrationOperation),
            Box::new(Initialize2MigrationOperation),
            Box::new(MigrateToOpenBookMigrationOperation),
            Box::new(MonitorStepMigrationOperation),
            Box::new(PreInitializeMigrationOperation),
            Box::new(SetParamsMigrationOperation),
            Box::new(SimulateInfoMigrationOperation),
            Box::new(SwapBaseInMigrationOperation),
            Box::new(SwapBaseOutMigrationOperation),
            Box::new(UpdateConfigAccountMigrationOperation),
            Box::new(WithdrawMigrationOperation),
            Box::new(WithdrawPnlMigrationOperation),
            Box::new(WithdrawSrmMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct RaydiumAmmV4InstructionWithMetadata(
    pub RaydiumAmmV4Instruction,
    pub carbon_core::instruction::InstructionMetadata,
    pub Vec<solana_instruction::AccountMeta>,
);

impl
    From<(
        RaydiumAmmV4Instruction,
        carbon_core::instruction::InstructionMetadata,
        Vec<solana_instruction::AccountMeta>,
    )> for RaydiumAmmV4InstructionWithMetadata
{
    fn from(
        value: (
            RaydiumAmmV4Instruction,
            carbon_core::instruction::InstructionMetadata,
            Vec<solana_instruction::AccountMeta>,
        ),
    ) -> Self {
        RaydiumAmmV4InstructionWithMetadata(value.0, value.1, value.2)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RaydiumAmmV4InstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RaydiumAmmV4InstructionWithMetadata(decoded_instruction, metadata, raw_accounts) = self;
        match decoded_instruction {
            RaydiumAmmV4Instruction::Initialize { data, .. } => {
                let row = initialize_row::InitializeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::Initialize2 { data, .. } => {
                let row = initialize2_row::Initialize2Row::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::MonitorStep { data, .. } => {
                let row = monitor_step_row::MonitorStepRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::Deposit { data, .. } => {
                let row = deposit_row::DepositRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::Withdraw { data, .. } => {
                let row = withdraw_row::WithdrawRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::MigrateToOpenBook { data, .. } => {
                let row = migrate_to_open_book_row::MigrateToOpenBookRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SetParams { data, .. } => {
                let row = set_params_row::SetParamsRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::WithdrawPnl { data, .. } => {
                let row = withdraw_pnl_row::WithdrawPnlRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::WithdrawSrm { data, .. } => {
                let row = withdraw_srm_row::WithdrawSrmRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SwapBaseIn { data, .. } => {
                let row = swap_base_in_row::SwapBaseInRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::PreInitialize { data, .. } => {
                let row = pre_initialize_row::PreInitializeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SwapBaseOut { data, .. } => {
                let row = swap_base_out_row::SwapBaseOutRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SimulateInfo { data, .. } => {
                let row = simulate_info_row::SimulateInfoRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::AdminCancelOrders { data, .. } => {
                let row = admin_cancel_orders_row::AdminCancelOrdersRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::CreateConfigAccount { data, .. } => {
                let row = create_config_account_row::CreateConfigAccountRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::UpdateConfigAccount { data, .. } => {
                let row = update_config_account_row::UpdateConfigAccountRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RaydiumAmmV4InstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RaydiumAmmV4InstructionWithMetadata(decoded_instruction, metadata, raw_accounts) = self;
        match decoded_instruction {
            RaydiumAmmV4Instruction::Initialize { data, .. } => {
                let row = initialize_row::InitializeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::Initialize2 { data, .. } => {
                let row = initialize2_row::Initialize2Row::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::MonitorStep { data, .. } => {
                let row = monitor_step_row::MonitorStepRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::Deposit { data, .. } => {
                let row = deposit_row::DepositRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::Withdraw { data, .. } => {
                let row = withdraw_row::WithdrawRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::MigrateToOpenBook { data, .. } => {
                let row = migrate_to_open_book_row::MigrateToOpenBookRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SetParams { data, .. } => {
                let row = set_params_row::SetParamsRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::WithdrawPnl { data, .. } => {
                let row = withdraw_pnl_row::WithdrawPnlRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::WithdrawSrm { data, .. } => {
                let row = withdraw_srm_row::WithdrawSrmRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SwapBaseIn { data, .. } => {
                let row = swap_base_in_row::SwapBaseInRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::PreInitialize { data, .. } => {
                let row = pre_initialize_row::PreInitializeRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SwapBaseOut { data, .. } => {
                let row = swap_base_out_row::SwapBaseOutRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::SimulateInfo { data, .. } => {
                let row = simulate_info_row::SimulateInfoRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::AdminCancelOrders { data, .. } => {
                let row = admin_cancel_orders_row::AdminCancelOrdersRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::CreateConfigAccount { data, .. } => {
                let row = create_config_account_row::CreateConfigAccountRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            RaydiumAmmV4Instruction::UpdateConfigAccount { data, .. } => {
                let row = update_config_account_row::UpdateConfigAccountRow::from_parts(
                    data.clone(),
                    metadata.clone(),
                    raw_accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
