//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::Json, serde_json};

// Data-carrying enum exposed as Json in GraphQL
pub type PlasmaEventGraphQL = Json;

impl From<crate::types::PlasmaEvent> for PlasmaEventGraphQL {
    fn from(original: crate::types::PlasmaEvent) -> Self {
        carbon_core::graphql::primitives::Json(
            serde_json::to_value(&original).unwrap_or(serde_json::Value::Null),
        )
    }
}
