export const RUST_KEYWORDS = [
    'as',
    'break',
    'const',
    'continue',
    'crate',
    'else',
    'enum',
    'extern',
    'false',
    'fn',
    'for',
    'if',
    'impl',
    'in',
    'let',
    'loop',
    'match',
    'mod',
    'move',
    'mut',
    'pub',
    'ref',
    'return',
    'self',
    'Self',
    'static',
    'struct',
    'super',
    'trait',
    'true',
    'type',
    'unsafe',
    'use',
    'where',
    'while',
    'abstract',
    'become',
    'box',
    'do',
    'final',
    'macro',
    'override',
    'priv',
    'typeof',
    'unsized',
    'virtual',
    'yield',
    'async',
    'await',
    'dyn',
    'try',
    'union',
    'macro_rules',
] as const;

export const RUST_KEYWORDS_SET = new Set<string>(RUST_KEYWORDS);

export function escapeRustKeyword(name: string): string {
    return RUST_KEYWORDS_SET.has(name) ? `r#${name}` : name;
}
