//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::{LiquidityPoolMarketCapBasedFeesGraphQL, LiquidityPoolTypeGraphQL},
    carbon_core::graphql::primitives::{U32, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ProtocolConfigParams")]
pub struct ProtocolConfigParamsGraphQL {
    pub create_pool_fee: U64,
    pub allow_create_pool: bool,
    pub supported_pool_type: LiquidityPoolTypeGraphQL,
    pub market_cap_based_fees: LiquidityPoolMarketCapBasedFeesGraphQL,
    pub initial_token_b_amount: f64,
    pub initial_token_a_amount: U64,
    pub default_leader_slot_window: U8,
    pub auto_staking_enabled: bool,
    pub sandwich_resistence_enabled: bool,
    pub buffer_bps: i32,
    pub auto_staking_threshold_bps: i32,
    pub token_a_decimals: U8,
    pub max_creator_trading_fee: U32,
    pub max_supply_per_wallet: U64,
    pub creator_trading_fee_trading_volume_threshold: f64,
    pub migration_market_cap_threshold: i32,
}

impl From<crate::types::ProtocolConfigParams> for ProtocolConfigParamsGraphQL {
    fn from(original: crate::types::ProtocolConfigParams) -> Self {
        Self {
            create_pool_fee: carbon_core::graphql::primitives::U64(original.create_pool_fee),
            allow_create_pool: original.allow_create_pool,
            supported_pool_type: original.supported_pool_type.into(),
            market_cap_based_fees: original.market_cap_based_fees.into(),
            initial_token_b_amount: original.initial_token_b_amount,
            initial_token_a_amount: carbon_core::graphql::primitives::U64(
                original.initial_token_a_amount,
            ),
            default_leader_slot_window: carbon_core::graphql::primitives::U8(
                original.default_leader_slot_window,
            ),
            auto_staking_enabled: original.auto_staking_enabled,
            sandwich_resistence_enabled: original.sandwich_resistence_enabled,
            buffer_bps: original.buffer_bps as i32,
            auto_staking_threshold_bps: original.auto_staking_threshold_bps as i32,
            token_a_decimals: carbon_core::graphql::primitives::U8(original.token_a_decimals),
            max_creator_trading_fee: carbon_core::graphql::primitives::U32(
                original.max_creator_trading_fee,
            ),
            max_supply_per_wallet: carbon_core::graphql::primitives::U64(
                original.max_supply_per_wallet,
            ),
            creator_trading_fee_trading_volume_threshold: original
                .creator_trading_fee_trading_volume_threshold,
            migration_market_cap_threshold: original.migration_market_cap_threshold as i32,
        }
    }
}
