//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::CancelOrderParamsGraphQL, carbon_core::graphql::primitives::U64,
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ReduceOrderParams")]
pub struct ReduceOrderParamsGraphQL {
    pub base_params: CancelOrderParamsGraphQL,
    pub size: U64,
}

impl From<crate::types::ReduceOrderParams> for ReduceOrderParamsGraphQL {
    fn from(original: crate::types::ReduceOrderParams) -> Self {
        Self {
            base_params: original.base_params.into(),
            size: carbon_core::graphql::primitives::U64(original.size),
        }
    }
}
