//! This code was AUTOGENERATED using the Codama library.
pub mod amount_to_ui_amount_row;
pub mod approve_checked_row;
pub mod approve_row;
pub mod batch_row;
pub mod burn_checked_row;
pub mod burn_row;
pub mod close_account_row;
pub mod freeze_account_row;
pub mod get_account_data_size_row;
pub mod initialize_account2_row;
pub mod initialize_account3_row;
pub mod initialize_account_row;
pub mod initialize_immutable_owner_row;
pub mod initialize_mint2_row;
pub mod initialize_mint_row;
pub mod initialize_multisig2_row;
pub mod initialize_multisig_row;
pub mod mint_to_checked_row;
pub mod mint_to_row;
pub mod revoke_row;
pub mod set_authority_row;
pub mod sync_native_row;
pub mod thaw_account_row;
pub mod transfer_checked_row;
pub mod transfer_row;
pub mod ui_amount_to_amount_row;
pub mod unwrap_lamports_row;
pub mod withdraw_excess_lamports_row;

pub use self::{
    amount_to_ui_amount_row::*, approve_checked_row::*, approve_row::*, batch_row::*,
    burn_checked_row::*, burn_row::*, close_account_row::*, freeze_account_row::*,
    get_account_data_size_row::*, initialize_account2_row::*, initialize_account3_row::*,
    initialize_account_row::*, initialize_immutable_owner_row::*, initialize_mint2_row::*,
    initialize_mint_row::*, initialize_multisig2_row::*, initialize_multisig_row::*,
    mint_to_checked_row::*, mint_to_row::*, revoke_row::*, set_authority_row::*,
    sync_native_row::*, thaw_account_row::*, transfer_checked_row::*, transfer_row::*,
    ui_amount_to_amount_row::*, unwrap_lamports_row::*, withdraw_excess_lamports_row::*,
};
use super::TokenProgramInstruction;

pub struct TokenProgramInstructionsMigration;

impl carbon_core::clickhouse::Migration for TokenProgramInstructionsMigration {
    fn app(&self) -> &str {
        "token-program"
    }

    fn name(&self) -> &str {
        "token_program_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::Operation>> {
        vec![
            Box::new(AmountToUiAmountRowMigrationOperation),
            Box::new(ApproveRowMigrationOperation),
            Box::new(ApproveCheckedRowMigrationOperation),
            Box::new(BatchRowMigrationOperation),
            Box::new(BurnRowMigrationOperation),
            Box::new(BurnCheckedRowMigrationOperation),
            Box::new(CloseAccountRowMigrationOperation),
            Box::new(FreezeAccountRowMigrationOperation),
            Box::new(GetAccountDataSizeRowMigrationOperation),
            Box::new(InitializeAccountRowMigrationOperation),
            Box::new(InitializeAccount2RowMigrationOperation),
            Box::new(InitializeAccount3RowMigrationOperation),
            Box::new(InitializeImmutableOwnerRowMigrationOperation),
            Box::new(InitializeMintRowMigrationOperation),
            Box::new(InitializeMint2RowMigrationOperation),
            Box::new(InitializeMultisigRowMigrationOperation),
            Box::new(InitializeMultisig2RowMigrationOperation),
            Box::new(MintToRowMigrationOperation),
            Box::new(MintToCheckedRowMigrationOperation),
            Box::new(RevokeRowMigrationOperation),
            Box::new(SetAuthorityRowMigrationOperation),
            Box::new(SyncNativeRowMigrationOperation),
            Box::new(ThawAccountRowMigrationOperation),
            Box::new(TransferRowMigrationOperation),
            Box::new(TransferCheckedRowMigrationOperation),
            Box::new(UiAmountToAmountRowMigrationOperation),
            Box::new(UnwrapLamportsRowMigrationOperation),
            Box::new(WithdrawExcessLamportsRowMigrationOperation),
        ]
    }
}

pub enum TokenProgramInstructionRow {
    AmountToUiAmount(AmountToUiAmountRow),
    Approve(ApproveRow),
    ApproveChecked(ApproveCheckedRow),
    Batch(BatchRow),
    Burn(BurnRow),
    BurnChecked(BurnCheckedRow),
    CloseAccount(CloseAccountRow),
    FreezeAccount(FreezeAccountRow),
    GetAccountDataSize(GetAccountDataSizeRow),
    InitializeAccount(InitializeAccountRow),
    InitializeAccount2(InitializeAccount2Row),
    InitializeAccount3(InitializeAccount3Row),
    InitializeImmutableOwner(InitializeImmutableOwnerRow),
    InitializeMint(InitializeMintRow),
    InitializeMint2(InitializeMint2Row),
    InitializeMultisig(InitializeMultisigRow),
    InitializeMultisig2(InitializeMultisig2Row),
    MintTo(MintToRow),
    MintToChecked(MintToCheckedRow),
    Revoke(RevokeRow),
    SetAuthority(SetAuthorityRow),
    SyncNative(SyncNativeRow),
    ThawAccount(ThawAccountRow),
    Transfer(TransferRow),
    TransferChecked(TransferCheckedRow),
    UiAmountToAmount(UiAmountToAmountRow),
    UnwrapLamports(UnwrapLamportsRow),
    WithdrawExcessLamports(WithdrawExcessLamportsRow),
}

pub struct TokenProgramInstructionMetadata(
    pub carbon_core::instruction::InstructionMetadata,
    pub TokenProgramInstruction,
);

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchInsert for TokenProgramInstructionMetadata {
    type Row = TokenProgramInstructionRow;

    async fn batch_insert(
        &self,
        rows: &mut Vec<Self::Row>,
    ) -> carbon_core::error::CarbonResult<()> {
        let Self(metadata, instruction) = self;

        match instruction {
            TokenProgramInstruction::AmountToUiAmount { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::AmountToUiAmount(
                    AmountToUiAmountRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::Approve { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::Approve(ApproveRow::try_from(
                    (data.clone(), metadata.clone(), accounts.clone()),
                )?));
            }
            TokenProgramInstruction::ApproveChecked { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::ApproveChecked(
                    ApproveCheckedRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::Batch { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::Batch(BatchRow::try_from((
                    data.clone(),
                    metadata.clone(),
                    accounts.clone(),
                ))?));
            }
            TokenProgramInstruction::Burn { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::Burn(BurnRow::try_from((
                    data.clone(),
                    metadata.clone(),
                    accounts.clone(),
                ))?));
            }
            TokenProgramInstruction::BurnChecked { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::BurnChecked(
                    BurnCheckedRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::CloseAccount { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::CloseAccount(
                    CloseAccountRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::FreezeAccount { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::FreezeAccount(
                    FreezeAccountRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::GetAccountDataSize { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::GetAccountDataSize(
                    GetAccountDataSizeRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeAccount { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeAccount(
                    InitializeAccountRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeAccount2 { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeAccount2(
                    InitializeAccount2Row::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeAccount3 { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeAccount3(
                    InitializeAccount3Row::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeImmutableOwner { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeImmutableOwner(
                    InitializeImmutableOwnerRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeMint { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeMint(
                    InitializeMintRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeMint2 { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeMint2(
                    InitializeMint2Row::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeMultisig { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeMultisig(
                    InitializeMultisigRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::InitializeMultisig2 { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::InitializeMultisig2(
                    InitializeMultisig2Row::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::MintTo { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::MintTo(MintToRow::try_from((
                    data.clone(),
                    metadata.clone(),
                    accounts.clone(),
                ))?));
            }
            TokenProgramInstruction::MintToChecked { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::MintToChecked(
                    MintToCheckedRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::Revoke { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::Revoke(RevokeRow::try_from((
                    data.clone(),
                    metadata.clone(),
                    accounts.clone(),
                ))?));
            }
            TokenProgramInstruction::SetAuthority { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::SetAuthority(
                    SetAuthorityRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::SyncNative { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::SyncNative(
                    SyncNativeRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::ThawAccount { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::ThawAccount(
                    ThawAccountRow::try_from((data.clone(), metadata.clone(), accounts.clone()))?,
                ));
            }
            TokenProgramInstruction::Transfer { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::Transfer(TransferRow::try_from(
                    (data.clone(), metadata.clone(), accounts.clone()),
                )?));
            }
            TokenProgramInstruction::TransferChecked { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::TransferChecked(
                    TransferCheckedRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::UiAmountToAmount { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::UiAmountToAmount(
                    UiAmountToAmountRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::UnwrapLamports { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::UnwrapLamports(
                    UnwrapLamportsRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
            TokenProgramInstruction::WithdrawExcessLamports { data, accounts, .. } => {
                rows.push(TokenProgramInstructionRow::WithdrawExcessLamports(
                    WithdrawExcessLamportsRow::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?,
                ));
            }
        }

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for TokenProgramInstructionRow {
    async fn batch_commit(
        &self,
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {
                if let Self::$variant(source) = self {
                    let branch_rows: Vec<$row> = rows
                        .iter()
                        .filter_map(|row| match row {
                            Self::$variant(row) => Some(row.clone()),
                            _ => None,
                        })
                        .collect();
                    return <$row as carbon_core::clickhouse::Insert>::insert(
                        source,
                        client,
                        &branch_rows,
                    )
                    .await;
                }
            };
        }

        commit_branch!(AmountToUiAmount, AmountToUiAmountRow);
        commit_branch!(Approve, ApproveRow);
        commit_branch!(ApproveChecked, ApproveCheckedRow);
        commit_branch!(Batch, BatchRow);
        commit_branch!(Burn, BurnRow);
        commit_branch!(BurnChecked, BurnCheckedRow);
        commit_branch!(CloseAccount, CloseAccountRow);
        commit_branch!(FreezeAccount, FreezeAccountRow);
        commit_branch!(GetAccountDataSize, GetAccountDataSizeRow);
        commit_branch!(InitializeAccount, InitializeAccountRow);
        commit_branch!(InitializeAccount2, InitializeAccount2Row);
        commit_branch!(InitializeAccount3, InitializeAccount3Row);
        commit_branch!(InitializeImmutableOwner, InitializeImmutableOwnerRow);
        commit_branch!(InitializeMint, InitializeMintRow);
        commit_branch!(InitializeMint2, InitializeMint2Row);
        commit_branch!(InitializeMultisig, InitializeMultisigRow);
        commit_branch!(InitializeMultisig2, InitializeMultisig2Row);
        commit_branch!(MintTo, MintToRow);
        commit_branch!(MintToChecked, MintToCheckedRow);
        commit_branch!(Revoke, RevokeRow);
        commit_branch!(SetAuthority, SetAuthorityRow);
        commit_branch!(SyncNative, SyncNativeRow);
        commit_branch!(ThawAccount, ThawAccountRow);
        commit_branch!(Transfer, TransferRow);
        commit_branch!(TransferChecked, TransferCheckedRow);
        commit_branch!(UiAmountToAmount, UiAmountToAmountRow);
        commit_branch!(UnwrapLamports, UnwrapLamportsRow);
        commit_branch!(WithdrawExcessLamports, WithdrawExcessLamportsRow);
        Ok(())
    }
}
