//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FreezeExecute")]
pub struct FreezeExecuteGraphQL {
    pub frozen: bool,
}

impl From<crate::types::FreezeExecute> for FreezeExecuteGraphQL {
    fn from(original: crate::types::FreezeExecute) -> Self {
        Self {
            frozen: original.frozen,
        }
    }
}
