//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "HookableLifecycleEvent")]
pub enum HookableLifecycleEventGraphQL {
    Create,
    Transfer,
    Burn,
    Update,
}

impl From<crate::types::HookableLifecycleEvent> for HookableLifecycleEventGraphQL {
    fn from(original: crate::types::HookableLifecycleEvent) -> Self {
        match original {
            crate::types::HookableLifecycleEvent::Create => Self::Create,
            crate::types::HookableLifecycleEvent::Transfer => Self::Transfer,
            crate::types::HookableLifecycleEvent::Burn => Self::Burn,
            crate::types::HookableLifecycleEvent::Update => Self::Update,
        }
    }
}
