//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::Pubkey, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VerifiedCreatorsSignature")]
pub struct VerifiedCreatorsSignatureGraphQL {
    pub address: Pubkey,
    pub verified: bool,
}

impl From<crate::types::VerifiedCreatorsSignature> for VerifiedCreatorsSignatureGraphQL {
    fn from(original: crate::types::VerifiedCreatorsSignature) -> Self {
        Self {
            address: carbon_core::graphql::primitives::Pubkey(original.address),
            verified: original.verified,
        }
    }
}
