//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct InitializeParams {
    pub token_controller: Pubkey,
    pub denylister: Pubkey,
    pub fee_recipient: Pubkey,
    pub min_fee_controller: Pubkey,
    pub min_fee: u32,
    pub message_body_version: u32,
}
