//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::deserialize::CarbonDeserialize, solana_pubkey::Pubkey};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct MarketMetaDataLogEvent {
    pub market: Pubkey,
    pub name: String,
    pub base_mint: Pubkey,
    pub quote_mint: Pubkey,
    pub base_decimals: u8,
    pub quote_decimals: u8,
    pub base_lot_size: i64,
    pub quote_lot_size: i64,
}

impl CarbonDeserialize for MarketMetaDataLogEvent {
    const DISCRIMINATOR: &'static [u8] = &[
        228, 69, 165, 46, 81, 203, 154, 29, 209, 87, 212, 236, 164, 58, 60, 117,
    ];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 16 {
            return None;
        }
        let discriminator = &data[0..16];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[16..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
