//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::U64, juniper::GraphQLObject};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LockedVestingParams")]
pub struct LockedVestingParamsGraphQL {
    pub amount_per_period: U64,
    pub cliff_duration_from_migration_time: U64,
    pub frequency: U64,
    pub number_of_period: U64,
    pub cliff_unlock_amount: U64,
}

impl From<crate::types::LockedVestingParams> for LockedVestingParamsGraphQL {
    fn from(original: crate::types::LockedVestingParams) -> Self {
        Self {
            amount_per_period: carbon_core::graphql::primitives::U64(original.amount_per_period),
            cliff_duration_from_migration_time: carbon_core::graphql::primitives::U64(
                original.cliff_duration_from_migration_time,
            ),
            frequency: carbon_core::graphql::primitives::U64(original.frequency),
            number_of_period: carbon_core::graphql::primitives::U64(original.number_of_period),
            cliff_unlock_amount: carbon_core::graphql::primitives::U64(
                original.cliff_unlock_amount,
            ),
        }
    }
}
