//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "TransferFeeOptions")]
pub struct TransferFeeOptionsGraphQL {
    pub amount: U64,
}

impl From<crate::types::TransferFeeOptions> for TransferFeeOptionsGraphQL {
    fn from(original: crate::types::TransferFeeOptions) -> Self {
        Self {
            amount: carbon_core::graphql::primitives::U64(original.amount),
        }
    }
}
