//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::OrchestratorFlagsGraphQL, carbon_core::graphql::primitives::U64,
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VaultSwapOptions")]
pub struct VaultSwapOptionsGraphQL {
    pub amount: U64,
    pub orchestrator_flags: OrchestratorFlagsGraphQL,
}

impl From<crate::types::VaultSwapOptions> for VaultSwapOptionsGraphQL {
    fn from(original: crate::types::VaultSwapOptions) -> Self {
        Self {
            amount: carbon_core::graphql::primitives::U64(original.amount),
            orchestrator_flags: original.orchestrator_flags.into(),
        }
    }
}
