//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct Deactivate {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DeactivateInstructionAccounts {
    pub stake: solana_pubkey::Pubkey,
    pub clock_sysvar: solana_pubkey::Pubkey,
    pub stake_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl Deactivate {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.is_empty() {
            return None;
        }
        let discriminator = &data[0..1];
        if discriminator != [5] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[1..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for Deactivate {
    type ArrangedAccounts = DeactivateInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let stake = next_account(&mut iter)?;
        let clock_sysvar = next_account(&mut iter)?;
        let stake_authority = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(DeactivateInstructionAccounts {
            stake,
            clock_sysvar,
            stake_authority,
            remaining: remaining.to_vec(),
        })
    }
}
