//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U128, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AddLiquidityEvent")]
pub struct AddLiquidityEventGraphQL {
    pub custody_key: Pubkey,
    pub pool_key: Pubkey,
    pub token_amount_in: U64,
    pub pre_pool_amount_usd: U128,
    pub token_amount_usd: U64,
    pub fee_bps: U64,
    pub token_amount_after_fee: U64,
    pub mint_amount_usd: U64,
    pub lp_amount: U64,
    pub post_pool_amount_usd: U128,
}

impl From<crate::types::AddLiquidityEvent> for AddLiquidityEventGraphQL {
    fn from(original: crate::types::AddLiquidityEvent) -> Self {
        Self {
            custody_key: carbon_core::graphql::primitives::Pubkey(original.custody_key),
            pool_key: carbon_core::graphql::primitives::Pubkey(original.pool_key),
            token_amount_in: carbon_core::graphql::primitives::U64(original.token_amount_in),
            pre_pool_amount_usd: carbon_core::graphql::primitives::U128(
                original.pre_pool_amount_usd,
            ),
            token_amount_usd: carbon_core::graphql::primitives::U64(original.token_amount_usd),
            fee_bps: carbon_core::graphql::primitives::U64(original.fee_bps),
            token_amount_after_fee: carbon_core::graphql::primitives::U64(
                original.token_amount_after_fee,
            ),
            mint_amount_usd: carbon_core::graphql::primitives::U64(original.mint_amount_usd),
            lp_amount: carbon_core::graphql::primitives::U64(original.lp_amount),
            post_pool_amount_usd: carbon_core::graphql::primitives::U128(
                original.post_pool_amount_usd,
            ),
        }
    }
}
