//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Json;

// Empty struct exposed as Json in GraphQL
pub type IncreasePositionPreSwapParamsGraphQL = Json;

impl From<crate::types::IncreasePositionPreSwapParams> for IncreasePositionPreSwapParamsGraphQL {
    fn from(_original: crate::types::IncreasePositionPreSwapParams) -> Self {
        carbon_core::graphql::primitives::Json(serde_json::Value::Null)
    }
}
