//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::StakedSettingsConfig,
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
};
/// (group admin only) Init the Staked Settings account, which is used to create
/// staked collateral banks, and must run before any staked collateral bank can
/// be created with `add_pool_permissionless`. Running this ix effectively opts
/// the group into the staked collateral feature.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct InitStakedSettings {
    pub settings: StakedSettingsConfig,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitStakedSettingsInstructionAccounts {
    pub marginfi_group: solana_pubkey::Pubkey,
    pub admin: solana_pubkey::Pubkey,
    pub fee_payer: solana_pubkey::Pubkey,
    pub staked_settings: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl InitStakedSettings {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [52, 35, 149, 44, 69, 86, 69, 80] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for InitStakedSettings {
    type ArrangedAccounts = InitStakedSettingsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let marginfi_group = next_account(&mut iter)?;
        let admin = next_account(&mut iter)?;
        let fee_payer = next_account(&mut iter)?;
        let staked_settings = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitStakedSettingsInstructionAccounts {
            marginfi_group,
            admin,
            fee_payer,
            staked_settings,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
