//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
/// (user) Deposit into a JupLend lending pool through a marginfi account.
/// * amount - in the underlying token (e.g., USDC), in native decimals
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct JuplendDeposit {
    pub amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct JuplendDepositInstructionAccounts {
    pub group: solana_pubkey::Pubkey,
    pub marginfi_account: solana_pubkey::Pubkey,
    pub authority: solana_pubkey::Pubkey,
    pub bank: solana_pubkey::Pubkey,
    pub signer_token_account: solana_pubkey::Pubkey,
    pub liquidity_vault_authority: solana_pubkey::Pubkey,
    pub liquidity_vault: solana_pubkey::Pubkey,
    pub mint: solana_pubkey::Pubkey,
    pub integration_acc1: solana_pubkey::Pubkey,
    pub f_token_mint: solana_pubkey::Pubkey,
    pub integration_acc2: solana_pubkey::Pubkey,
    pub lending_admin: solana_pubkey::Pubkey,
    pub supply_token_reserves_liquidity: solana_pubkey::Pubkey,
    pub lending_supply_position_on_liquidity: solana_pubkey::Pubkey,
    pub rate_model: solana_pubkey::Pubkey,
    pub vault: solana_pubkey::Pubkey,
    pub liquidity: solana_pubkey::Pubkey,
    pub liquidity_program: solana_pubkey::Pubkey,
    pub rewards_rate_model: solana_pubkey::Pubkey,
    pub juplend_program: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl JuplendDeposit {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [114, 11, 218, 81, 183, 165, 143, 255] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for JuplendDeposit {
    type ArrangedAccounts = JuplendDepositInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let group = next_account(&mut iter)?;
        let marginfi_account = next_account(&mut iter)?;
        let authority = next_account(&mut iter)?;
        let bank = next_account(&mut iter)?;
        let signer_token_account = next_account(&mut iter)?;
        let liquidity_vault_authority = next_account(&mut iter)?;
        let liquidity_vault = next_account(&mut iter)?;
        let mint = next_account(&mut iter)?;
        let integration_acc1 = next_account(&mut iter)?;
        let f_token_mint = next_account(&mut iter)?;
        let integration_acc2 = next_account(&mut iter)?;
        let lending_admin = next_account(&mut iter)?;
        let supply_token_reserves_liquidity = next_account(&mut iter)?;
        let lending_supply_position_on_liquidity = next_account(&mut iter)?;
        let rate_model = next_account(&mut iter)?;
        let vault = next_account(&mut iter)?;
        let liquidity = next_account(&mut iter)?;
        let liquidity_program = next_account(&mut iter)?;
        let rewards_rate_model = next_account(&mut iter)?;
        let juplend_program = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(JuplendDepositInstructionAccounts {
            group,
            marginfi_account,
            authority,
            bank,
            signer_token_account,
            liquidity_vault_authority,
            liquidity_vault,
            mint,
            integration_acc1,
            f_token_mint,
            integration_acc2,
            lending_admin,
            supply_token_reserves_liquidity,
            lending_supply_position_on_liquidity,
            rate_model,
            vault,
            liquidity,
            liquidity_program,
            rewards_rate_model,
            juplend_program,
            token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
