//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account_utils::next_account,
    deserialize::{ArrangeAccounts, CarbonDeserialize},
};
/// (admin only) Set the destination wallet for permissionless fee withdrawals.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct LendingPoolUpdateFeesDestinationAccount {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct LendingPoolUpdateFeesDestinationAccountInstructionAccounts {
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub group: solana_pubkey::Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub bank: solana_pubkey::Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub admin: solana_pubkey::Pubkey,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub destination_account: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CarbonDeserialize for LendingPoolUpdateFeesDestinationAccount {
    const DISCRIMINATOR: &'static [u8] = &[102, 4, 121, 243, 237, 110, 95, 13];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for LendingPoolUpdateFeesDestinationAccount {
    type ArrangedAccounts = LendingPoolUpdateFeesDestinationAccountInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let group = next_account(&mut iter)?;
        let bank = next_account(&mut iter)?;
        let admin = next_account(&mut iter)?;
        let destination_account = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(LendingPoolUpdateFeesDestinationAccountInstructionAccounts {
            group,
            bank,
            admin,
            destination_account,
            remaining: remaining.to_vec(),
        })
    }
}
