//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
/// (permissionless) Zero out `emissions_outstanding` on a balance after
/// emissions are disabled on the bank.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct LendingAccountClearEmissions {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct LendingAccountClearEmissionsInstructionAccounts {
    pub marginfi_account: solana_pubkey::Pubkey,
    pub bank: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl LendingAccountClearEmissions {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [239, 4, 221, 98, 45, 167, 201, 244] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for LendingAccountClearEmissions {
    type ArrangedAccounts = LendingAccountClearEmissionsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let marginfi_account = next_account(&mut iter)?;
        let bank = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(LendingAccountClearEmissionsInstructionAccounts {
            marginfi_account,
            bank,
            remaining: remaining.to_vec(),
        })
    }
}
