//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    instruction::InstructionMetadata,
    postgres::{
        metadata::InstructionRowMetadata,
        primitives::{U16, U64},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct CreateAmmConfigRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub index: U16,
    pub trade_fee_rate: U64,
    pub protocol_fee_rate: U64,
    pub fund_fee_rate: U64,
    pub create_pool_fee: U64,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl CreateAmmConfigRow {
    pub fn from_parts(
        source: crate::instructions::create_amm_config::CreateAmmConfig,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            index: source.index.into(),
            trade_fee_rate: source.trade_fee_rate.into(),
            protocol_fee_rate: source.protocol_fee_rate.into(),
            fund_fee_rate: source.fund_fee_rate.into(),
            create_pool_fee: source.create_pool_fee.into(),
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<CreateAmmConfigRow> for crate::instructions::create_amm_config::CreateAmmConfig {
    type Error = carbon_core::error::Error;
    fn try_from(source: CreateAmmConfigRow) -> Result<Self, Self::Error> {
        Ok(Self {
            index: source.index.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            trade_fee_rate: *source.trade_fee_rate,
            protocol_fee_rate: *source.protocol_fee_rate,
            fund_fee_rate: *source.fund_fee_rate,
            create_pool_fee: *source.create_pool_fee,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::create_amm_config::CreateAmmConfig
{
    fn table() -> &'static str {
        "create_amm_config_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "index",
            "trade_fee_rate",
            "protocol_fee_rate",
            "fund_fee_rate",
            "create_pool_fee",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for CreateAmmConfigRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO create_amm_config_instruction (
                "index",
                "trade_fee_rate",
                "protocol_fee_rate",
                "fund_fee_rate",
                "create_pool_fee",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            )"#,
        )
        .bind(self.index)
        .bind(&self.trade_fee_rate)
        .bind(&self.protocol_fee_rate)
        .bind(&self.fund_fee_rate)
        .bind(&self.create_pool_fee)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for CreateAmmConfigRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO create_amm_config_instruction (
                "index",
                "trade_fee_rate",
                "protocol_fee_rate",
                "fund_fee_rate",
                "create_pool_fee",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "index" = EXCLUDED."index",
                "trade_fee_rate" = EXCLUDED."trade_fee_rate",
                "protocol_fee_rate" = EXCLUDED."protocol_fee_rate",
                "fund_fee_rate" = EXCLUDED."fund_fee_rate",
                "create_pool_fee" = EXCLUDED."create_pool_fee",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(self.index)
        .bind(&self.trade_fee_rate)
        .bind(&self.protocol_fee_rate)
        .bind(&self.fund_fee_rate)
        .bind(&self.create_pool_fee)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for CreateAmmConfigRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM create_amm_config_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for CreateAmmConfigRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM create_amm_config_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct CreateAmmConfigMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for CreateAmmConfigMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS create_amm_config_instruction (
                -- Instruction data
                "index" INT4 NOT NULL,
                "trade_fee_rate" NUMERIC(20) NOT NULL,
                "protocol_fee_rate" NUMERIC(20) NOT NULL,
                "fund_fee_rate" NUMERIC(20) NOT NULL,
                "create_pool_fee" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS create_amm_config_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
