//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account::AccountMetadata,
    postgres::{
        metadata::AccountRowMetadata,
        primitives::{Pubkey, U16, U64},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct LimitOrderRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub lb_pair: Pubkey,
    pub owner: Pubkey,
    pub bin_count: U16,
    pub padding0: Vec<u8>,
    pub padding1: Vec<U64>,
}

impl LimitOrderRow {
    pub fn from_parts(
        source: crate::accounts::limit_order::LimitOrder,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            lb_pair: source.lb_pair.into(),
            owner: source.owner.into(),
            bin_count: source.bin_count.into(),
            padding0: source.padding0.to_vec(),
            padding1: source
                .padding1
                .into_iter()
                .map(|element| element.into())
                .collect(),
        }
    }
}

impl TryFrom<LimitOrderRow> for crate::accounts::limit_order::LimitOrder {
    type Error = carbon_core::error::Error;
    fn try_from(source: LimitOrderRow) -> Result<Self, Self::Error> {
        Ok(Self {
            lb_pair: *source.lb_pair,
            owner: *source.owner,
            bin_count: source.bin_count.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            padding0: source.padding0.as_slice().try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert padding from postgres primitive: expected 14 bytes"
                        .to_string(),
                )
            })?,
            padding1: source
                .padding1
                .into_iter()
                .map(|element| Ok(*element))
                .collect::<Result<Vec<_>, carbon_core::error::Error>>()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to collect array elements".to_string(),
                    )
                })?
                .try_into()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert array element to primitive".to_string(),
                    )
                })?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::limit_order::LimitOrder {
    fn table() -> &'static str {
        "limit_order_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "lb_pair",
            "owner",
            "bin_count",
            "padding0",
            "padding1",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for LimitOrderRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO limit_order_account (
                "lb_pair",
                "owner",
                "bin_count",
                "padding0",
                "padding1",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#,
        )
        .bind(self.lb_pair)
        .bind(self.owner)
        .bind(self.bin_count)
        .bind(&self.padding0)
        .bind(&self.padding1)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for LimitOrderRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO limit_order_account (
                "lb_pair",
                "owner",
                "bin_count",
                "padding0",
                "padding1",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "lb_pair" = EXCLUDED."lb_pair",
                "owner" = EXCLUDED."owner",
                "bin_count" = EXCLUDED."bin_count",
                "padding0" = EXCLUDED."padding0",
                "padding1" = EXCLUDED."padding1",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.lb_pair)
        .bind(self.owner)
        .bind(self.bin_count)
        .bind(&self.padding0)
        .bind(&self.padding1)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for LimitOrderRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM limit_order_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Lookup for LimitOrderRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM limit_order_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct LimitOrderMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for LimitOrderMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS limit_order_account (
                -- Account data
                "lb_pair" BYTEA NOT NULL,
                "owner" BYTEA NOT NULL,
                "bin_count" INT4 NOT NULL,
                "padding0" BYTEA NOT NULL,
                "padding1" NUMERIC(20)[] NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS limit_order_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
