//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::GroupEventHeaderGraphQL,
    carbon_core::graphql::primitives::{Pubkey, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LendingPoolSuperAdminDepositEvent")]
pub struct LendingPoolSuperAdminDepositEventGraphQL {
    pub header: GroupEventHeaderGraphQL,
    pub bank: Pubkey,
    pub mint: Pubkey,
    pub transfer_amount: U64,
    pub vault_inflow_amount: U64,
}

impl From<crate::types::LendingPoolSuperAdminDepositEvent>
    for LendingPoolSuperAdminDepositEventGraphQL
{
    fn from(original: crate::types::LendingPoolSuperAdminDepositEvent) -> Self {
        Self {
            header: original.header.into(),
            bank: carbon_core::graphql::primitives::Pubkey(original.bank),
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            transfer_amount: carbon_core::graphql::primitives::U64(original.transfer_amount),
            vault_inflow_amount: carbon_core::graphql::primitives::U64(
                original.vault_inflow_amount,
            ),
        }
    }
}
