//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "UserStatus")]
pub enum UserStatusGraphQL {
    Active,
    BeingLiquidated,
    Bankrupt,
    ReduceOnly,
    AdvancedLp,
    ProtectedMakerOrders,
}

impl From<crate::types::UserStatus> for UserStatusGraphQL {
    fn from(original: crate::types::UserStatus) -> Self {
        match original {
            crate::types::UserStatus::Active => Self::Active,
            crate::types::UserStatus::BeingLiquidated => Self::BeingLiquidated,
            crate::types::UserStatus::Bankrupt => Self::Bankrupt,
            crate::types::UserStatus::ReduceOnly => Self::ReduceOnly,
            crate::types::UserStatus::AdvancedLp => Self::AdvancedLp,
            crate::types::UserStatus::ProtectedMakerOrders => Self::ProtectedMakerOrders,
        }
    }
}
