//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InsuranceClaim")]
pub struct InsuranceClaimGraphQL {
    pub revenue_withdraw_since_last_settle: I64,
    pub max_revenue_withdraw_per_period: U64,
    pub quote_max_insurance: U64,
    pub quote_settled_insurance: U64,
    pub last_revenue_withdraw_ts: I64,
}

impl From<crate::types::InsuranceClaim> for InsuranceClaimGraphQL {
    fn from(original: crate::types::InsuranceClaim) -> Self {
        Self {
            revenue_withdraw_since_last_settle: carbon_core::graphql::primitives::I64(
                original.revenue_withdraw_since_last_settle,
            ),
            max_revenue_withdraw_per_period: carbon_core::graphql::primitives::U64(
                original.max_revenue_withdraw_per_period,
            ),
            quote_max_insurance: carbon_core::graphql::primitives::U64(
                original.quote_max_insurance,
            ),
            quote_settled_insurance: carbon_core::graphql::primitives::U64(
                original.quote_settled_insurance,
            ),
            last_revenue_withdraw_ts: carbon_core::graphql::primitives::I64(
                original.last_revenue_withdraw_ts,
            ),
        }
    }
}
