//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "OrderActionExplanation")]
pub enum OrderActionExplanationGraphQL {
    None,
    InsufficientFreeCollateral,
    OraclePriceBreachedLimitPrice,
    MarketOrderFilledToLimitPrice,
    OrderExpired,
    Liquidation,
    OrderFilledWithAMM,
    OrderFilledWithAMMJit,
    OrderFilledWithMatch,
    OrderFilledWithMatchJit,
    MarketExpired,
    RiskingIncreasingOrder,
    ReduceOnlyOrderIncreasedPosition,
    OrderFillWithSerum,
    NoBorrowLiquidity,
    OrderFillWithPhoenix,
    OrderFilledWithAMMJitLPSplit,
    OrderFilledWithLPJit,
    DeriskLp,
    OrderFilledWithOpenbookV2,
    TransferPerpPosition,
}

impl From<crate::types::OrderActionExplanation> for OrderActionExplanationGraphQL {
    fn from(original: crate::types::OrderActionExplanation) -> Self {
        match original {
            crate::types::OrderActionExplanation::None => Self::None,
            crate::types::OrderActionExplanation::InsufficientFreeCollateral => {
                Self::InsufficientFreeCollateral
            }
            crate::types::OrderActionExplanation::OraclePriceBreachedLimitPrice => {
                Self::OraclePriceBreachedLimitPrice
            }
            crate::types::OrderActionExplanation::MarketOrderFilledToLimitPrice => {
                Self::MarketOrderFilledToLimitPrice
            }
            crate::types::OrderActionExplanation::OrderExpired => Self::OrderExpired,
            crate::types::OrderActionExplanation::Liquidation => Self::Liquidation,
            crate::types::OrderActionExplanation::OrderFilledWithAMM => Self::OrderFilledWithAMM,
            crate::types::OrderActionExplanation::OrderFilledWithAMMJit => {
                Self::OrderFilledWithAMMJit
            }
            crate::types::OrderActionExplanation::OrderFilledWithMatch => {
                Self::OrderFilledWithMatch
            }
            crate::types::OrderActionExplanation::OrderFilledWithMatchJit => {
                Self::OrderFilledWithMatchJit
            }
            crate::types::OrderActionExplanation::MarketExpired => Self::MarketExpired,
            crate::types::OrderActionExplanation::RiskingIncreasingOrder => {
                Self::RiskingIncreasingOrder
            }
            crate::types::OrderActionExplanation::ReduceOnlyOrderIncreasedPosition => {
                Self::ReduceOnlyOrderIncreasedPosition
            }
            crate::types::OrderActionExplanation::OrderFillWithSerum => Self::OrderFillWithSerum,
            crate::types::OrderActionExplanation::NoBorrowLiquidity => Self::NoBorrowLiquidity,
            crate::types::OrderActionExplanation::OrderFillWithPhoenix => {
                Self::OrderFillWithPhoenix
            }
            crate::types::OrderActionExplanation::OrderFilledWithAMMJitLPSplit => {
                Self::OrderFilledWithAMMJitLPSplit
            }
            crate::types::OrderActionExplanation::OrderFilledWithLPJit => {
                Self::OrderFilledWithLPJit
            }
            crate::types::OrderActionExplanation::DeriskLp => Self::DeriskLp,
            crate::types::OrderActionExplanation::OrderFilledWithOpenbookV2 => {
                Self::OrderFilledWithOpenbookV2
            }
            crate::types::OrderActionExplanation::TransferPerpPosition => {
                Self::TransferPerpPosition
            }
        }
    }
}
