//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "RevenueShareOrderBitFlag")]
pub enum RevenueShareOrderBitFlagGraphQL {
    Init,
    Open,
    Completed,
    Referral,
}

impl From<crate::types::RevenueShareOrderBitFlag> for RevenueShareOrderBitFlagGraphQL {
    fn from(original: crate::types::RevenueShareOrderBitFlag) -> Self {
        match original {
            crate::types::RevenueShareOrderBitFlag::Init => Self::Init,
            crate::types::RevenueShareOrderBitFlag::Open => Self::Open,
            crate::types::RevenueShareOrderBitFlag::Completed => Self::Completed,
            crate::types::RevenueShareOrderBitFlag::Referral => Self::Referral,
        }
    }
}
