//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "TokenProgramFlag")]
pub enum TokenProgramFlagGraphQL {
    Token2022,
    TransferHook,
}

impl From<crate::types::TokenProgramFlag> for TokenProgramFlagGraphQL {
    fn from(original: crate::types::TokenProgramFlag) -> Self {
        match original {
            crate::types::TokenProgramFlag::Token2022 => Self::Token2022,
            crate::types::TokenProgramFlag::TransferHook => Self::TransferHook,
        }
    }
}
