//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Json, U64},
    juniper::GraphQLObject,
    serde_json,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "TokenSellExactIn")]
pub struct TokenSellExactInGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub amount_in: U64,
    pub allow_partial_fill: bool,
    pub price_threshold: Option<Json>,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::TokenSellExactInRow> for TokenSellExactInGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::TokenSellExactInRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            amount_in: carbon_core::graphql::primitives::U64(*row.amount_in),
            allow_partial_fill: row.allow_partial_fill,
            price_threshold: row.price_threshold.map(|v| {
                carbon_core::graphql::primitives::Json(
                    serde_json::to_value(v).unwrap_or(serde_json::Value::Null),
                )
            }),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
