//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::deserialize::CarbonDeserialize, solana_pubkey::Pubkey};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TradingFeesSplitEventEvent {
    pub amount: u64,
    #[cfg_attr(
        feature = "base58",
        serde(serialize_with = "carbon_core::convert::base58::serialize")
    )]
    pub creator: Pubkey,
}

impl CarbonDeserialize for TradingFeesSplitEventEvent {
    const DISCRIMINATOR: &'static [u8] = &[113, 60, 159, 17, 253, 174, 135, 122];

    fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
