//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U128, U64, U8},
    juniper::GraphQLObject,
    serde_json,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitializeLpPool")]
pub struct InitializeLpPoolGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub lp_pool_id: U8,
    pub min_mint_fee: I64,
    pub max_aum: U128,
    pub max_settle_quote_amount_per_market: U64,
    pub whitelist_mint: Pubkey,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::InitializeLpPoolRow> for InitializeLpPoolGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::InitializeLpPoolRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            lp_pool_id: carbon_core::graphql::primitives::U8((*row.lp_pool_id) as u8),
            min_mint_fee: carbon_core::graphql::primitives::I64(row.min_mint_fee),
            max_aum: carbon_core::graphql::primitives::U128(*row.max_aum),
            max_settle_quote_amount_per_market: carbon_core::graphql::primitives::U64(
                *row.max_settle_quote_amount_per_market,
            ),
            whitelist_mint: carbon_core::graphql::primitives::Pubkey(row.whitelist_mint.0),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
