//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct FeeConfigUpdated {
    pub admin: Pubkey,
    pub old_bump_lower_bps: u16,
    pub old_bump_middle_bps: u16,
    pub old_bump_upper_bps: u16,
    pub old_buy_fee_bps: u16,
    pub old_refund_fee_bps: [u16; 4],
    pub old_spin_fee_lamports: u64,
    pub old_create_launch_fee_lamports: u64,
    pub old_dev_bundle_fee_bps: u16,
    pub old_migrate_fee_bps: u16,
    pub old_dev_fee_bps: u16,
    pub old_min_buy_fee_bps: u16,
    pub new_bump_lower_bps: u16,
    pub new_bump_middle_bps: u16,
    pub new_bump_upper_bps: u16,
    pub new_buy_fee_bps: u16,
    pub new_refund_fee_bps: [u16; 4],
    pub new_spin_fee_lamports: u64,
    pub new_create_launch_fee_lamports: u64,
    pub new_dev_bundle_fee_bps: u16,
    pub new_migrate_fee_bps: u16,
    pub new_dev_fee_bps: u16,
    pub new_min_buy_fee_bps: u16,
    pub timestamp: i64,
}

