//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "PausedToggledEvent")]
pub struct PausedToggledEventGraphQL {
    pub is_paused: bool,
}

impl From<crate::types::PausedToggledEvent> for PausedToggledEventGraphQL {
    fn from(original: crate::types::PausedToggledEvent) -> Self {
        Self {
            is_paused: original.is_paused,
        }
    }
}
