//! This code was AUTOGENERATED using the Codama library.
#[derive(clickhouse::Row, serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct CreateProLiquidityPoolRow {
    pub __signature: String,
    pub __instruction_index: u32,
    pub __stack_height: u32,
    pub __slot: u64,
    pub __accounts: String,
    pub data: String,
}

impl
    TryFrom<(
        crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPool,
        carbon_core::instruction::InstructionMetadata,
        crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPoolInstructionAccounts,
    )> for CreateProLiquidityPoolRow
{
    type Error = carbon_core::error::Error;

    fn try_from(
        (source, metadata, accounts): (
            crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPool,
            carbon_core::instruction::InstructionMetadata,
            crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPoolInstructionAccounts,
        ),
    ) -> Result<Self, Self::Error> {
        let accounts = serde_json::to_string(&accounts)
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        let data = serde_json::to_string(&source)
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;

        Ok(Self {
            __signature: metadata.transaction_metadata.signature.to_string(),
            __instruction_index: metadata.index,
            __stack_height: metadata.stack_height,
            __slot: metadata.transaction_metadata.slot,
            __accounts: accounts,
            data,
        })
    }
}

impl TryFrom<CreateProLiquidityPoolRow>
    for (
        crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPool,
        crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPoolInstructionAccounts,
        CreateProLiquidityPoolRow,
    )
{
    type Error = carbon_core::error::Error;

    fn try_from(value: CreateProLiquidityPoolRow) -> Result<Self, Self::Error> {
        let source: crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPool =
            serde_json::from_str(&value.data)
                .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        let accounts: crate::instructions::create_pro_liquidity_pool::CreateProLiquidityPoolInstructionAccounts = serde_json::from_str(&value.__accounts)
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;

        Ok((source, accounts, value))
    }
}

#[cfg(feature = "clickhouse-cluster")]
impl carbon_core::clickhouse::ClusterTable for CreateProLiquidityPoolRow {
    fn local_table() -> &'static str {
        "heaven_create_pro_liquidity_pool_instruction_local"
    }

    fn distributed_table() -> &'static str {
        "heaven_create_pro_liquidity_pool_instruction"
    }
}

#[cfg(not(feature = "clickhouse-cluster"))]
impl carbon_core::clickhouse::Table for CreateProLiquidityPoolRow {
    fn table() -> &'static str {
        "heaven_create_pro_liquidity_pool_instruction"
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::Insert for CreateProLiquidityPoolRow {
    async fn insert(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        if rows.is_empty() {
            return Ok(());
        }

        let mut insert = client
            .insert::<Self>("heaven_create_pro_liquidity_pool_instruction")
            .await
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;

        for row in rows {
            insert
                .write(row)
                .await
                .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        }

        insert
            .end()
            .await
            .map_err(|error| carbon_core::error::Error::Custom(error.to_string()))?;
        Ok(())
    }
}

pub struct CreateProLiquidityPoolRowMigrationOperation;

#[cfg(feature = "clickhouse-cluster")]
#[async_trait::async_trait]
impl carbon_core::clickhouse::Operation for CreateProLiquidityPoolRowMigrationOperation {
    async fn up(
        &self,
        client: &clickhouse::Client,
        config: &carbon_core::clickhouse::MigrationConfig,
    ) -> clickhouse::error::Result<()> {
        let cluster_name = &config.cluster_name;
        let replica_path = format!(
            "/clickhouse/tables/{}/heaven_create_pro_liquidity_pool_instruction_local",
            config.shard_name,
        );

        client
            .query(&format!(
                r#"
                    CREATE TABLE IF NOT EXISTS heaven_create_pro_liquidity_pool_instruction_local ON CLUSTER {cluster} (
                        __signature String,
                        __instruction_index UInt32,
                        __stack_height UInt32,
                        __slot UInt64,
                        __accounts String,
                        data String
                    )
                    ENGINE = ReplicatedReplacingMergeTree('{replica_path}', '{{replica}}')
                    ORDER BY (__signature, __instruction_index, __stack_height)
                "#,
                cluster = cluster_name,
                replica_path = replica_path,
            ))
            .execute()
            .await?;

        client
            .query(&format!(
                r#"
                    CREATE TABLE IF NOT EXISTS heaven_create_pro_liquidity_pool_instruction ON CLUSTER {cluster} AS heaven_create_pro_liquidity_pool_instruction_local
                    ENGINE = Distributed({cluster}, currentDatabase(), heaven_create_pro_liquidity_pool_instruction_local, rand())
                "#,
                cluster = cluster_name,
            ))
            .execute()
            .await?;

        Ok(())
    }

    async fn down(
        &self,
        client: &clickhouse::Client,
        config: &carbon_core::clickhouse::MigrationConfig,
    ) -> clickhouse::error::Result<()> {
        let cluster_name = &config.cluster_name;

        client
            .query(&format!(
                "DROP TABLE IF EXISTS heaven_create_pro_liquidity_pool_instruction ON CLUSTER {cluster}",
                cluster = cluster_name,
            ))
            .execute()
            .await?;

        client
            .query(&format!(
                "DROP TABLE IF EXISTS heaven_create_pro_liquidity_pool_instruction_local ON CLUSTER {cluster}",
                cluster = cluster_name,
            ))
            .execute()
            .await?;

        Ok(())
    }
}

#[cfg(not(feature = "clickhouse-cluster"))]
#[async_trait::async_trait]
impl carbon_core::clickhouse::Operation for CreateProLiquidityPoolRowMigrationOperation {
    async fn up(&self, client: &clickhouse::Client) -> clickhouse::error::Result<()> {
        client
            .query(
                r#"
                    CREATE TABLE IF NOT EXISTS heaven_create_pro_liquidity_pool_instruction (
                        __signature String,
                        __instruction_index UInt32,
                        __stack_height UInt32,
                        __slot UInt64,
                        __accounts String,
                        data String
                    )
                    ENGINE = ReplacingMergeTree()
                    ORDER BY (__signature, __instruction_index, __stack_height)
                "#,
            )
            .execute()
            .await?;

        Ok(())
    }

    async fn down(&self, client: &clickhouse::Client) -> clickhouse::error::Result<()> {
        client
            .query("DROP TABLE IF EXISTS heaven_create_pro_liquidity_pool_instruction")
            .execute()
            .await?;

        Ok(())
    }
}
