//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "Withdrawal")]
pub enum WithdrawalGraphQL {
    In,
    Out,
}

impl From<crate::types::Withdrawal> for WithdrawalGraphQL {
    fn from(original: crate::types::Withdrawal) -> Self {
        match original {
            crate::types::Withdrawal::In => Self::In,
            crate::types::Withdrawal::Out => Self::Out,
        }
    }
}
