//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct WithdrawDestToken {
    pub withdraw_amount: u64,
    pub coin_amount: u64,
    pub pc_amount: u64,
    pub dest_token_coin: Pubkey,
    pub dest_token_pc: Pubkey,
}
