//! This code was AUTOGENERATED using the Codama library.
pub mod add_liquidity_row;
pub mod initialize_lp_position_row;
pub mod initialize_pool_row;
pub mod log_row;
pub mod remove_liquidity_row;
pub mod renounce_liquidity_row;
pub mod swap_row;
pub mod transfer_liquidity_row;
pub mod withdraw_lp_fees_row;
pub mod withdraw_protocol_fees_row;

pub use self::{
    add_liquidity_row::*, initialize_lp_position_row::*, initialize_pool_row::*, log_row::*,
    remove_liquidity_row::*, renounce_liquidity_row::*, swap_row::*, transfer_liquidity_row::*,
    withdraw_lp_fees_row::*, withdraw_protocol_fees_row::*,
};
use super::GavelInstruction;

pub struct GavelInstructionsMigration;

impl carbon_core::clickhouse::Migration for GavelInstructionsMigration {
    fn app(&self) -> &str {
        "gavel"
    }

    fn name(&self) -> &str {
        "gavel_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::Operation>> {
        vec![
            Box::new(AddLiquidityRowMigrationOperation),
            Box::new(InitializeLpPositionRowMigrationOperation),
            Box::new(InitializePoolRowMigrationOperation),
            Box::new(LogRowMigrationOperation),
            Box::new(RemoveLiquidityRowMigrationOperation),
            Box::new(RenounceLiquidityRowMigrationOperation),
            Box::new(SwapRowMigrationOperation),
            Box::new(TransferLiquidityRowMigrationOperation),
            Box::new(WithdrawLpFeesRowMigrationOperation),
            Box::new(WithdrawProtocolFeesRowMigrationOperation),
        ]
    }
}

pub enum GavelInstructionRow {
    AddLiquidity(AddLiquidityRow),
    InitializeLpPosition(InitializeLpPositionRow),
    InitializePool(InitializePoolRow),
    Log(LogRow),
    RemoveLiquidity(RemoveLiquidityRow),
    RenounceLiquidity(RenounceLiquidityRow),
    Swap(SwapRow),
    TransferLiquidity(TransferLiquidityRow),
    WithdrawLpFees(WithdrawLpFeesRow),
    WithdrawProtocolFees(WithdrawProtocolFeesRow),
}

pub struct GavelInstructionMetadata<'a>(
    pub &'a carbon_core::instruction::InstructionMetadata,
    pub &'a GavelInstruction,
);

impl<'a> carbon_core::clickhouse::BatchInsert for GavelInstructionMetadata<'a> {
    type Row = GavelInstructionRow;

    fn batch_insert(&self, rows: &mut Vec<Self::Row>) -> carbon_core::error::CarbonResult<()> {
        let &Self(metadata, instruction) = self;

        macro_rules! insert_branch {
            ($variant:ident, $row:ty) => {
                if let GavelInstruction::$variant { data, accounts, .. } = instruction {
                    rows.push(GavelInstructionRow::$variant(<$row>::try_from((
                        data.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    ))?));
                    return Ok(());
                }
            };
        }

        insert_branch!(AddLiquidity, AddLiquidityRow);
        insert_branch!(InitializeLpPosition, InitializeLpPositionRow);
        insert_branch!(InitializePool, InitializePoolRow);
        insert_branch!(Log, LogRow);
        insert_branch!(RemoveLiquidity, RemoveLiquidityRow);
        insert_branch!(RenounceLiquidity, RenounceLiquidityRow);
        insert_branch!(Swap, SwapRow);
        insert_branch!(TransferLiquidity, TransferLiquidityRow);
        insert_branch!(WithdrawLpFees, WithdrawLpFeesRow);
        insert_branch!(WithdrawProtocolFees, WithdrawProtocolFeesRow);

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for GavelInstructionRow {
    async fn batch_commit(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {{
                let branch_rows: Vec<$row> = rows
                    .iter()
                    .filter_map(|row| match row {
                        Self::$variant(row) => Some(row.clone()),
                        _ => None,
                    })
                    .collect();

                if !branch_rows.is_empty() {
                    <$row as carbon_core::clickhouse::Insert>::insert(client, &branch_rows).await?;
                }
            }};
        }

        commit_branch!(AddLiquidity, AddLiquidityRow);
        commit_branch!(InitializeLpPosition, InitializeLpPositionRow);
        commit_branch!(InitializePool, InitializePoolRow);
        commit_branch!(Log, LogRow);
        commit_branch!(RemoveLiquidity, RemoveLiquidityRow);
        commit_branch!(RenounceLiquidity, RenounceLiquidityRow);
        commit_branch!(Swap, SwapRow);
        commit_branch!(TransferLiquidity, TransferLiquidityRow);
        commit_branch!(WithdrawLpFees, WithdrawLpFeesRow);
        commit_branch!(WithdrawProtocolFees, WithdrawProtocolFeesRow);

        Ok(())
    }
}
