//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{instruction::InstructionMetadata, postgres::metadata::InstructionRowMetadata};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct UpdatePerpMarketOracleSlotDelayOverrideRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub oracle_slot_delay_override: i8,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl UpdatePerpMarketOracleSlotDelayOverrideRow {
    pub fn from_parts(
        source: crate::instructions::update_perp_market_oracle_slot_delay_override::UpdatePerpMarketOracleSlotDelayOverride,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            oracle_slot_delay_override: source.oracle_slot_delay_override,
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<UpdatePerpMarketOracleSlotDelayOverrideRow> for crate::instructions::update_perp_market_oracle_slot_delay_override::UpdatePerpMarketOracleSlotDelayOverride {
    type Error = carbon_core::error::Error;
    fn try_from(source: UpdatePerpMarketOracleSlotDelayOverrideRow) -> Result<Self, Self::Error> {
        Ok(Self {
            oracle_slot_delay_override: source.oracle_slot_delay_override,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::update_perp_market_oracle_slot_delay_override::UpdatePerpMarketOracleSlotDelayOverride {
    fn table() -> &'static str {
        "update_perp_market_oracle_slot_delay_override_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "oracle_slot_delay_override",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for UpdatePerpMarketOracleSlotDelayOverrideRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO update_perp_market_oracle_slot_delay_override_instruction (
                "oracle_slot_delay_override",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            )"#,
        )
        .bind(self.oracle_slot_delay_override)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for UpdatePerpMarketOracleSlotDelayOverrideRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO update_perp_market_oracle_slot_delay_override_instruction (
                "oracle_slot_delay_override",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "oracle_slot_delay_override" = EXCLUDED."oracle_slot_delay_override",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(self.oracle_slot_delay_override)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for UpdatePerpMarketOracleSlotDelayOverrideRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM update_perp_market_oracle_slot_delay_override_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for UpdatePerpMarketOracleSlotDelayOverrideRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM update_perp_market_oracle_slot_delay_override_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct UpdatePerpMarketOracleSlotDelayOverrideMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres>
    for UpdatePerpMarketOracleSlotDelayOverrideMigrationOperation
{
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS update_perp_market_oracle_slot_delay_override_instruction (
                -- Instruction data
                "oracle_slot_delay_override" INT2 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"DROP TABLE IF EXISTS update_perp_market_oracle_slot_delay_override_instruction"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }
}
