//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    instruction::InstructionMetadata,
    postgres::{metadata::InstructionRowMetadata, primitives::U16},
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct UpdateStateMaxNumberOfSubAccountsRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub max_number_of_sub_accounts: U16,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl UpdateStateMaxNumberOfSubAccountsRow {
    pub fn from_parts(
        source: crate::instructions::update_state_max_number_of_sub_accounts::UpdateStateMaxNumberOfSubAccounts,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            max_number_of_sub_accounts: source.max_number_of_sub_accounts.into(),
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<UpdateStateMaxNumberOfSubAccountsRow> for crate::instructions::update_state_max_number_of_sub_accounts::UpdateStateMaxNumberOfSubAccounts {
    type Error = carbon_core::error::Error;
    fn try_from(source: UpdateStateMaxNumberOfSubAccountsRow) -> Result<Self, Self::Error> {
        Ok(Self {
            max_number_of_sub_accounts: source.max_number_of_sub_accounts.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::update_state_max_number_of_sub_accounts::UpdateStateMaxNumberOfSubAccounts {
    fn table() -> &'static str {
        "update_state_max_number_of_sub_accounts_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "max_number_of_sub_accounts",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for UpdateStateMaxNumberOfSubAccountsRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO update_state_max_number_of_sub_accounts_instruction (
                "max_number_of_sub_accounts",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            )"#,
        )
        .bind(self.max_number_of_sub_accounts)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for UpdateStateMaxNumberOfSubAccountsRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO update_state_max_number_of_sub_accounts_instruction (
                "max_number_of_sub_accounts",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "max_number_of_sub_accounts" = EXCLUDED."max_number_of_sub_accounts",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(self.max_number_of_sub_accounts)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for UpdateStateMaxNumberOfSubAccountsRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM update_state_max_number_of_sub_accounts_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for UpdateStateMaxNumberOfSubAccountsRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM update_state_max_number_of_sub_accounts_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct UpdateStateMaxNumberOfSubAccountsMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres>
    for UpdateStateMaxNumberOfSubAccountsMigrationOperation
{
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS update_state_max_number_of_sub_accounts_instruction (
                -- Instruction data
                "max_number_of_sub_accounts" INT4 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS update_state_max_number_of_sub_accounts_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
