//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct OpenbookV2Decoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb");

pub mod accounts;
pub mod events;
#[cfg(feature = "graphql")]
pub mod graphql;
pub mod instructions;
pub mod types;
