[package]
name = "carbon-pump-amm-decoder"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = []
serde = ["dep:serde", "dep:serde-big-array"]
postgres = [
    "carbon-core/postgres",
    "dep:sqlx",
    "dep:async-trait",
    "dep:sqlx_migrator",
    "serde",
]

[dependencies]
# Core dependencies
carbon-core = { workspace = true, default-features = false }
solana-pubkey = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true, default-features = false }

# Serialization (optional)
serde = { workspace = true, features = ["derive"], optional = true }
serde-big-array = { version = "0.5.1", optional = true }

# Postgres dependencies (optional)
sqlx = { workspace = true, features = ["postgres", "rust_decimal"], optional = true }
async-trait = { version = "0.1", optional = true }
sqlx_migrator = { version = "0.17.0", optional = true }

[dev-dependencies]
carbon-test-utils = { workspace = true }

