use carbon_core::{borsh, CarbonDeserialize};

#[derive(
    CarbonDeserialize, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq, Clone, Hash,
)]
pub enum InstructionName {
    Unknown,
    MintV1,
    Redeem,
    CancelRedeem,
    Transfer,
    Delegate,
    DecompressV1,
    Compress,
    Burn,
    CreateTree,
    VerifyCreator,
    UnverifyCreator,
    VerifyCollection,
    UnverifyCollection,
    SetAndVerifyCollection,
    MintToCollectionV1,
    SetDecompressibleState,
    UpdateMetadata,
    BurnV2,
    CollectV2,
    CreateTreeV2,
    DelegateAndFreezeV2,
    DelegateV2,
    FreezeV2,
    MintV2,
    SetCollectionV2,
    SetNonTransferableV2,
    ThawAndRevokeV2,
    ThawV2,
    TransferV2,
    UnverifyCreatorV2,
    UpdateAssetDataV2,
    UpdateMetadataV2,
    VerifyCreatorV2,
}
