//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::FeeBrackets,
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct CreatorSetProMarketCapCreatorFee {
    pub fees: FeeBrackets,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreatorSetProMarketCapCreatorFeeInstructionAccounts {
    pub liquidity_pool_state: solana_pubkey::Pubkey,
    pub creator: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CreatorSetProMarketCapCreatorFee {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [117, 206, 56, 2, 28, 37, 236, 235] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for CreatorSetProMarketCapCreatorFee {
    type ArrangedAccounts = CreatorSetProMarketCapCreatorFeeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let liquidity_pool_state = next_account(&mut iter)?;
        let creator = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CreatorSetProMarketCapCreatorFeeInstructionAccounts {
            liquidity_pool_state,
            creator,
            remaining: remaining.to_vec(),
        })
    }
}
