[package]
name = "carbon-fetch-ix"
version = "0.9.1"
edition = { workspace = true }
description = "Fetch IX for Carbon tests"
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
keywords = ["solana", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "carbon-fetch-ix-cli"
path = "src/main.rs"

[dependencies]
solana-client = { workspace = true }
solana-commitment-config = { workspace = true }
solana-signature = { workspace = true }
solana-transaction-status = { workspace = true }

bs58 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
