//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::SwapParams,
    carbon_core::{account_utils::next_account, borsh, deserialize::ArrangeAccounts},
};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct Swap {
    pub params: SwapParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapInstructionAccounts {
    pub protocol_fee: solana_pubkey::Pubkey,
    pub source_mint: solana_pubkey::Pubkey,
    pub destination_mint: solana_pubkey::Pubkey,
    pub fee_wallet: solana_pubkey::Pubkey,
    pub source_token_account: solana_pubkey::Pubkey,
    pub destination_token_account: solana_pubkey::Pubkey,
    pub authority: solana_pubkey::Pubkey,
    pub authority_source: solana_pubkey::Pubkey,
    pub authority_destination: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub amm_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub source_token_program: solana_pubkey::Pubkey,
    pub destination_token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl Swap {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[248, 198, 158, 145, 225, 117, 135, 200] {
            return None;
        }

        let mut data_slice = data;
        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for Swap {
    type ArrangedAccounts = SwapInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let protocol_fee = next_account(&mut iter)?;
        let source_mint = next_account(&mut iter)?;
        let destination_mint = next_account(&mut iter)?;
        let fee_wallet = next_account(&mut iter)?;
        let source_token_account = next_account(&mut iter)?;
        let destination_token_account = next_account(&mut iter)?;
        let authority = next_account(&mut iter)?;
        let authority_source = next_account(&mut iter)?;
        let authority_destination = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let amm_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let source_token_program = next_account(&mut iter)?;
        let destination_token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(SwapInstructionAccounts {
            protocol_fee,
            source_mint,
            destination_mint,
            fee_wallet,
            source_token_account,
            destination_token_account,
            authority,
            authority_source,
            authority_destination,
            payer,
            amm_program,
            system_program,
            associated_token_program,
            source_token_program,
            destination_token_program,
            remaining: remaining.to_vec(),
        })
    }
}
