//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "BookSideOrderTree")]
pub enum BookSideOrderTreeGraphQL {
    Fixed,
    OraclePegged,
}

impl From<crate::types::BookSideOrderTree> for BookSideOrderTreeGraphQL {
    fn from(original: crate::types::BookSideOrderTree) -> Self {
        match original {
            crate::types::BookSideOrderTree::Fixed => Self::Fixed,
            crate::types::BookSideOrderTree::OraclePegged => Self::OraclePegged,
        }
    }
}
