//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct LogUserSwapBalancesStart {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct LogUserSwapBalancesStartInstructionAccounts {
    pub maker: solana_pubkey::Pubkey,
    pub input_mint: solana_pubkey::Pubkey,
    pub output_mint: solana_pubkey::Pubkey,
    pub input_ta: solana_pubkey::Pubkey,
    pub output_ta: solana_pubkey::Pubkey,
    pub pda_referrer: Option<solana_pubkey::Pubkey>,
    pub swap_program_id: solana_pubkey::Pubkey,
    pub user_swap_balance_state: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub rent: solana_pubkey::Pubkey,
    pub sysvar_instructions: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl LogUserSwapBalancesStart {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [133, 108, 23, 15, 226, 215, 176, 95] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for LogUserSwapBalancesStart {
    type ArrangedAccounts = LogUserSwapBalancesStartInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let maker = next_account(&mut iter)?;
        let input_mint = next_account(&mut iter)?;
        let output_mint = next_account(&mut iter)?;
        let input_ta = next_account(&mut iter)?;
        let output_ta = next_account(&mut iter)?;
        let pda_referrer = next_account(&mut iter);
        let swap_program_id = next_account(&mut iter)?;
        let user_swap_balance_state = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let rent = next_account(&mut iter)?;
        let sysvar_instructions = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(LogUserSwapBalancesStartInstructionAccounts {
            maker,
            input_mint,
            output_mint,
            input_ta,
            output_ta,
            pda_referrer,
            swap_program_id,
            user_swap_balance_state,
            system_program,
            rent,
            sysvar_instructions,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
