//! This code was AUTOGENERATED using the Codama library.
pub mod amm_config_row;
pub mod observation_state_row;
pub mod permission_row;
pub mod pool_state_row;

pub use self::{amm_config_row::*, observation_state_row::*, permission_row::*, pool_state_row::*};
use super::RaydiumCpmmAccount;

pub struct RaydiumCpmmAccountsMigration;

impl carbon_core::clickhouse::Migration for RaydiumCpmmAccountsMigration {
    fn app(&self) -> &str {
        "raydium-cpmm"
    }

    fn name(&self) -> &str {
        "raydium_cpmm_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn carbon_core::clickhouse::Operation>> {
        vec![
            Box::new(AmmConfigRowMigrationOperation),
            Box::new(ObservationStateRowMigrationOperation),
            Box::new(PermissionRowMigrationOperation),
            Box::new(PoolStateRowMigrationOperation),
        ]
    }
}

pub enum RaydiumCpmmAccountRow {
    AmmConfig(AmmConfigRow),
    ObservationState(ObservationStateRow),
    Permission(PermissionRow),
    PoolState(PoolStateRow),
}

pub struct RaydiumCpmmAccountMetadata<'a>(
    pub &'a carbon_core::account::AccountMetadata,
    pub &'a RaydiumCpmmAccount,
);

impl<'a> carbon_core::clickhouse::BatchInsert for RaydiumCpmmAccountMetadata<'a> {
    type Row = RaydiumCpmmAccountRow;

    fn batch_insert(&self, rows: &mut Vec<Self::Row>) -> carbon_core::error::CarbonResult<()> {
        let &Self(metadata, account) = self;

        macro_rules! insert_branch {
            ($variant:ident, $row:ty, boxed) => {
                if let RaydiumCpmmAccount::$variant(account) = account {
                    rows.push(RaydiumCpmmAccountRow::$variant(<$row>::try_from((
                        account.as_ref().clone(),
                        metadata.clone(),
                    ))?));
                    return Ok(());
                }
            };
            ($variant:ident, $row:ty, plain) => {
                if let RaydiumCpmmAccount::$variant(account) = account {
                    rows.push(RaydiumCpmmAccountRow::$variant(<$row>::try_from((
                        account.clone(),
                        metadata.clone(),
                    ))?));
                    return Ok(());
                }
            };
        }

        insert_branch!(AmmConfig, AmmConfigRow, boxed);
        insert_branch!(ObservationState, ObservationStateRow, boxed);
        insert_branch!(Permission, PermissionRow, boxed);
        insert_branch!(PoolState, PoolStateRow, boxed);

        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::clickhouse::BatchCommit for RaydiumCpmmAccountRow {
    async fn batch_commit(
        client: &clickhouse::Client,
        rows: &[Self],
    ) -> carbon_core::error::CarbonResult<()> {
        macro_rules! commit_branch {
            ($variant:ident, $row:ty) => {{
                let branch_rows: Vec<$row> = rows
                    .iter()
                    .filter_map(|row| match row {
                        Self::$variant(row) => Some(row.clone()),
                        _ => None,
                    })
                    .collect();

                if !branch_rows.is_empty() {
                    <$row as carbon_core::clickhouse::Insert>::insert(client, &branch_rows).await?;
                }
            }};
        }

        commit_branch!(AmmConfig, AmmConfigRow);
        commit_branch!(ObservationState, ObservationStateRow);
        commit_branch!(Permission, PermissionRow);
        commit_branch!(PoolState, PoolStateRow);

        Ok(())
    }
}
