//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::TransferOutOfEscrowArgs,
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TransferOutOfEscrow {
    pub transfer_out_of_escrow_args: TransferOutOfEscrowArgs,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TransferOutOfEscrowInstructionAccounts {
    pub escrow: solana_pubkey::Pubkey,
    pub metadata: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub attribute_mint: solana_pubkey::Pubkey,
    pub attribute_src: solana_pubkey::Pubkey,
    pub attribute_dst: solana_pubkey::Pubkey,
    pub escrow_mint: solana_pubkey::Pubkey,
    pub escrow_account: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub ata_program: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub sysvar_instructions: solana_pubkey::Pubkey,
    pub authority: Option<solana_pubkey::Pubkey>,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl TransferOutOfEscrow {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.is_empty() {
            return None;
        }
        let discriminator = &data[0..1];
        if discriminator != [40] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[1..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for TransferOutOfEscrow {
    type ArrangedAccounts = TransferOutOfEscrowInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let escrow = next_account(&mut iter)?;
        let metadata = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let attribute_mint = next_account(&mut iter)?;
        let attribute_src = next_account(&mut iter)?;
        let attribute_dst = next_account(&mut iter)?;
        let escrow_mint = next_account(&mut iter)?;
        let escrow_account = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let ata_program = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let sysvar_instructions = next_account(&mut iter)?;
        let authority = next_account(&mut iter);

        let remaining = iter.as_slice();

        Some(TransferOutOfEscrowInstructionAccounts {
            escrow,
            metadata,
            payer,
            attribute_mint,
            attribute_src,
            attribute_dst,
            escrow_mint,
            escrow_account,
            system_program,
            ata_program,
            token_program,
            sysvar_instructions,
            authority,
            remaining: remaining.to_vec(),
        })
    }
}
