//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::BorrowFromCustodyParams,
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct BorrowFromCustody {
    pub params: BorrowFromCustodyParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BorrowFromCustodyInstructionAccounts {
    pub owner: solana_pubkey::Pubkey,
    pub perpetuals: solana_pubkey::Pubkey,
    pub pool: solana_pubkey::Pubkey,
    pub custody: solana_pubkey::Pubkey,
    pub transfer_authority: solana_pubkey::Pubkey,
    pub borrow_position: solana_pubkey::Pubkey,
    pub custody_token_account: solana_pubkey::Pubkey,
    pub user_token_account: solana_pubkey::Pubkey,
    pub lp_token_mint: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl BorrowFromCustody {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [153, 183, 65, 65, 113, 33, 249, 45] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for BorrowFromCustody {
    type ArrangedAccounts = BorrowFromCustodyInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let owner = next_account(&mut iter)?;
        let perpetuals = next_account(&mut iter)?;
        let pool = next_account(&mut iter)?;
        let custody = next_account(&mut iter)?;
        let transfer_authority = next_account(&mut iter)?;
        let borrow_position = next_account(&mut iter)?;
        let custody_token_account = next_account(&mut iter)?;
        let user_token_account = next_account(&mut iter)?;
        let lp_token_mint = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(BorrowFromCustodyInstructionAccounts {
            owner,
            perpetuals,
            pool,
            custody,
            transfer_authority,
            borrow_position,
            custody_token_account,
            user_token_account,
            lp_token_mint,
            token_program,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
