//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::OperatorSetCustodyConfigParams,
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct OperatorSetCustodyConfig {
    pub params: OperatorSetCustodyConfigParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct OperatorSetCustodyConfigInstructionAccounts {
    pub operator: solana_pubkey::Pubkey,
    pub custody: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl OperatorSetCustodyConfig {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [166, 137, 92, 204, 145, 224, 24, 218] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for OperatorSetCustodyConfig {
    type ArrangedAccounts = OperatorSetCustodyConfigInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let operator = next_account(&mut iter)?;
        let custody = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(OperatorSetCustodyConfigInstructionAccounts {
            operator,
            custody,
            remaining: remaining.to_vec(),
        })
    }
}
