//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// UpdateConfigAccount.param values.
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "ConfigParam")]
pub enum ConfigParamGraphQL {
    PnlOwner,
    CancelOrderOwner,
    CreatePoolFee,
}

impl From<crate::types::ConfigParam> for ConfigParamGraphQL {
    fn from(original: crate::types::ConfigParam) -> Self {
        match original {
            crate::types::ConfigParam::PnlOwner => Self::PnlOwner,
            crate::types::ConfigParam::CancelOrderOwner => Self::CancelOrderOwner,
            crate::types::ConfigParam::CreatePoolFee => Self::CreatePoolFee,
        }
    }
}
