//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RefundLogClosedEvent {
    pub launch: Pubkey,
    pub keeper_refund: u64,
}

impl RefundLogClosedEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[178, 80, 213, 171, 238, 233, 143, 219] {
            return None;
        }

        let mut data_slice = data;
        data_slice = &data_slice[8..];
        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
