//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U128},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "EvtPermanentLockPosition")]
pub struct EvtPermanentLockPositionGraphQL {
    pub pool: Pubkey,
    pub position: Pubkey,
    pub lock_liquidity_amount: U128,
    pub total_permanent_locked_liquidity: U128,
}

impl From<crate::types::EvtPermanentLockPosition> for EvtPermanentLockPositionGraphQL {
    fn from(original: crate::types::EvtPermanentLockPosition) -> Self {
        Self {
            pool: carbon_core::graphql::primitives::Pubkey(original.pool),
            position: carbon_core::graphql::primitives::Pubkey(original.position),
            lock_liquidity_amount: carbon_core::graphql::primitives::U128(
                original.lock_liquidity_amount,
            ),
            total_permanent_locked_liquidity: carbon_core::graphql::primitives::U128(
                original.total_permanent_locked_liquidity,
            ),
        }
    }
}
