//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::graphql::PoolFeeParametersGraphQL,
    carbon_core::graphql::primitives::{U128, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitializeCustomizablePoolParameters")]
pub struct InitializeCustomizablePoolParametersGraphQL {
    pub pool_fees: PoolFeeParametersGraphQL,
    pub sqrt_min_price: U128,
    pub sqrt_max_price: U128,
    pub has_alpha_vault: bool,
    pub liquidity: U128,
    pub sqrt_price: U128,
    pub activation_type: U8,
    pub collect_fee_mode: U8,
    pub activation_point: Option<U64>,
}

impl From<crate::types::InitializeCustomizablePoolParameters>
    for InitializeCustomizablePoolParametersGraphQL
{
    fn from(original: crate::types::InitializeCustomizablePoolParameters) -> Self {
        Self {
            pool_fees: original.pool_fees.into(),
            sqrt_min_price: carbon_core::graphql::primitives::U128(original.sqrt_min_price),
            sqrt_max_price: carbon_core::graphql::primitives::U128(original.sqrt_max_price),
            has_alpha_vault: original.has_alpha_vault,
            liquidity: carbon_core::graphql::primitives::U128(original.liquidity),
            sqrt_price: carbon_core::graphql::primitives::U128(original.sqrt_price),
            activation_type: carbon_core::graphql::primitives::U8(original.activation_type),
            collect_fee_mode: carbon_core::graphql::primitives::U8(original.collect_fee_mode),
            activation_point: original.activation_point.map(U64),
        }
    }
}
