//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    instruction::InstructionMetadata,
    postgres::{metadata::InstructionRowMetadata, primitives::Pubkey},
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct InitializeConfidentialTransferFeeRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub authority: Option<Pubkey>,
    pub withdraw_withheld_authority_el_gamal_pubkey: Option<Pubkey>,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl InitializeConfidentialTransferFeeRow {
    pub fn from_parts(
        source: crate::instructions::initialize_confidential_transfer_fee::InitializeConfidentialTransferFee,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            authority: source.authority.map(|value| value.into()),
            withdraw_withheld_authority_el_gamal_pubkey: source
                .withdraw_withheld_authority_el_gamal_pubkey
                .map(|value| value.into()),
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<InitializeConfidentialTransferFeeRow>
    for crate::instructions::initialize_confidential_transfer_fee::InitializeConfidentialTransferFee
{
    type Error = carbon_core::error::Error;
    fn try_from(source: InitializeConfidentialTransferFeeRow) -> Result<Self, Self::Error> {
        Ok(Self {
            authority: source.authority.map(|value| *value),
            withdraw_withheld_authority_el_gamal_pubkey: source
                .withdraw_withheld_authority_el_gamal_pubkey
                .map(|value| *value),
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::initialize_confidential_transfer_fee::InitializeConfidentialTransferFee
{
    fn table() -> &'static str {
        "initialize_confidential_transfer_fee_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "authority",
            "withdraw_withheld_authority_el_gamal_pubkey",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for InitializeConfidentialTransferFeeRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO initialize_confidential_transfer_fee_instruction (
                "authority",
                "withdraw_withheld_authority_el_gamal_pubkey",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#,
        )
        .bind(self.authority)
        .bind(self.withdraw_withheld_authority_el_gamal_pubkey)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for InitializeConfidentialTransferFeeRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO initialize_confidential_transfer_fee_instruction (
                "authority",
                "withdraw_withheld_authority_el_gamal_pubkey",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "authority" = EXCLUDED."authority",
                "withdraw_withheld_authority_el_gamal_pubkey" = EXCLUDED."withdraw_withheld_authority_el_gamal_pubkey",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#)
        .bind(self.authority)
        .bind(self.withdraw_withheld_authority_el_gamal_pubkey)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for InitializeConfidentialTransferFeeRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM initialize_confidential_transfer_fee_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for InitializeConfidentialTransferFeeRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM initialize_confidential_transfer_fee_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct InitializeConfidentialTransferFeeMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres>
    for InitializeConfidentialTransferFeeMigrationOperation
{
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS initialize_confidential_transfer_fee_instruction (
                -- Instruction data
                "authority" BYTEA,
                "withdraw_withheld_authority_el_gamal_pubkey" BYTEA,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS initialize_confidential_transfer_fee_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
