//! This code was AUTOGENERATED using the Codama library.
use {crate::types::ElevationGroup, solana_pubkey::Pubkey};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct LendingMarket {
    /// Version of lending market
    pub version: u64,
    /// Bump seed for derived authority address
    pub bump_seed: u64,
    /// Owner authority which can add new reserves
    pub lending_market_owner: Pubkey,
    /// Temporary cache of the lending market owner, used in
    /// update_lending_market_owner
    pub lending_market_owner_cached: Pubkey,
    /// Currency market prices are quoted in
    /// e.g. "USD" null padded
    /// (`*b"USD\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"`) or
    /// a SPL token mint pubkey
    pub quote_currency: [u8; 32],
    /// Referral fee for the lending market, as bps out of the total protocol
    /// fee
    pub referral_fee_bps: u16,
    pub emergency_mode: u8,
    /// Whether the obligations on this market should be subject to
    /// auto-deleveraging after deposit or borrow limit is crossed.
    /// Besides this flag, the particular reserve's flag also needs to be
    /// enabled (logical `AND`). **NOTE:** this also affects the individual
    /// "target LTV" deleveraging.
    pub autodeleverage_enabled: u8,
    pub borrow_disabled: u8,
    /// Refresh price from oracle only if it's older than this percentage of the
    /// price max age. e.g. if the max age is set to 100s and this is set to
    /// 80%, the price will be refreshed if it's older than 80s.
    /// Price is always refreshed if this set to 0.
    pub price_refresh_trigger_to_max_age_pct: u8,
    /// Percentage of the total borrowed value in an obligation available for
    /// liquidation
    pub liquidation_max_debt_close_factor_pct: u8,
    /// Minimum acceptable unhealthy LTV before max_debt_close_factor_pct
    /// becomes 100%
    pub insolvency_risk_unhealthy_ltv_pct: u8,
    /// Minimum liquidation value threshold triggering full liquidation for an
    /// obligation, in full units of the quote currency (e.g. `2` means
    /// "$2", not "2 lamports of USDC").
    pub min_full_liquidation_value_threshold: u64,
    /// Max allowed liquidation value in one ix call
    pub max_liquidatable_debt_market_value_at_once: u64,
    /// [DEPRECATED] Global maximum unhealthy borrow value allowed for any
    /// obligation
    pub reserved0: [u8; 8],
    /// Global maximum allowed borrow value allowed for any obligation
    pub global_allowed_borrow_value: u64,
    /// The address of the emergency council, in charge of taking emergency
    /// actions on the market (e.g., enabling emergency mode)
    pub emergency_council: Pubkey,
    /// [DEPRECATED] Reward points multiplier per obligation type
    pub reserved1: [u8; 8],
    /// Elevation groups are used to group together reserves that have the same
    /// risk parameters and can bump the ltv and liquidation threshold
    pub elevation_groups: [ElevationGroup; 32],
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub elevation_group_padding: [u64; 90],
    /// Min net value accepted to be found in a position after any lending
    /// action in an obligation (scaled by quote currency decimals)
    pub min_net_value_in_obligation_sf: u128,
    /// Minimum value to enforce smallest ltv priority checks on the collateral
    /// reserves on liquidation
    pub min_value_skip_liquidation_ltv_checks: u64,
    /// Market name, zero-padded.
    pub name: [u8; 32],
    /// Minimum value to enforce highest borrow factor priority checks on the
    /// debt reserves on liquidation
    pub min_value_skip_liquidation_bf_checks: u64,
    /// Time (in seconds) that must pass before liquidation is allowed on an
    /// obligation that has been individually marked for auto-deleveraging.
    pub individual_autodeleverage_margin_call_period_secs: u64,
    /// Minimum amount of deposit at creation of a reserve to prevent artificial
    /// inflation Note: this amount cannot be recovered, the ctoken
    /// associated are never minted
    pub min_initial_deposit_amount: u64,
    /// Whether the obligation orders should be evaluated during liquidations.
    pub obligation_order_execution_enabled: u8,
    /// Whether the lending market is set as immutable.
    pub immutable: u8,
    /// Whether new obligation orders can be created.
    /// Note: updating or cancelling existing orders is *not* affected by this
    /// flag.
    pub obligation_order_creation_enabled: u8,
    /// Whether the liquidation operations that are triggered by price changes
    /// should be disabled. This includes regular liquidation (i.e. LTV
    /// exceeding the unhealthy threshold) and some obligation orders'
    /// execution. *Caution:* this flag is *disabling* the liquidations when
    /// `1` - contrary to all the other
    ///
    /// liquidation-driving flags (see e.g. [Self::autodeleverage_enabled]).
    pub price_triggered_liquidation_disabled: u8,
    /// Whether the debts that reached their reserve's
    /// [ReserveConfig::debt_maturity_timestamp] can be liquidated.
    pub mature_reserve_debt_liquidation_enabled: u8,
    /// Whether the [Obligation::borrows] that reached their
    /// [ReserveConfig::debt_term_seconds] can be liquidated.
    pub obligation_borrow_debt_term_liquidation_enabled: u8,
    /// Whether new borrow orders can be created.
    /// Note: updating or cancelling existing orders is *not* affected by this
    /// flag.
    pub borrow_order_creation_enabled: u8,
    /// Whether the existing borrow orders can be filled.
    pub borrow_order_execution_enabled: u8,
    /// Authority that can propose creating of new reserves but cannot enable
    /// them.
    pub proposer_authority: Pubkey,
    /// Minimum value that can be filled in a single `fill_borrow_order()` call,
    /// in full units of the quote currency (e.g. `2` means "$2", not "2
    /// lamports of USDC").
    pub min_borrow_order_fill_value: u64,
    /// Whether any new withdraw tickets can be issued (i.e. whether new
    /// requests can enter the withdraw queue).
    pub withdraw_ticket_issuance_enabled: u8,
    /// Whether the existing withdraw tickets can be redeemed (i.e. whether the
    /// tickets can be used to transfer accumulated pending liquidity to
    /// destination accounts).
    pub withdraw_ticket_redemption_enabled: u8,
    /// Whether the owners can enable the borrow rollover/migration on their
    /// obligations. *Note 1:* the actual execution of (different kinds of)
    /// rollovers are enabled/disabled by:
    /// - [Self::fixed_term_rollover_window_duration_seconds],
    /// - [Self::open_term_rollover_window_duration_seconds],
    /// - [Self::obligation_borrow_migration_to_fixed_execution_enabled].
    ///
    /// Note 2: when this configuration is disabled, the obligation owners can
    /// still disable their rollover (i.e. set the obligation's flags to
    /// zeroes).
    pub obligation_borrow_rollover_configuration_enabled: u8,
    /// Whether the actual execution of a "migration to fixed" rollover flavor
    /// is allowed.
    /// See [FixedTermBorrowRolloverConfig::migration_to_fixed_enabled].
    pub obligation_borrow_migration_to_fixed_execution_enabled: u8,
    pub padding2: [u8; 4],
    /// Minimum value that can be withdrawn in a single
    /// `withdraw_queued_liquidity()` call, in full units of the quote
    /// currency (e.g. `2` means "$2", not "2 lamports of USDC").
    pub min_withdraw_queued_liquidity_value: u64,
    /// A configurable time window (right before the end of a fixed debt term)
    /// during which an auto-rollover into another *fixed* rate/term can
    /// happen. When zeroed, this rollover mode is effectively disabled.
    /// Can only be enabled when [Self::min_partial_rollover_value] is
    /// configured. See [FixedTermBorrowRolloverConfig].
    pub fixed_term_rollover_window_duration_seconds: u64,
    /// A configurable time window (right before the end of a fixed debt term)
    /// during which an auto-rollover into a *variable* (indefinite)
    /// rate/term can happen. When zeroed, this rollover mode is effectively
    /// disabled. Can only be enabled when
    /// [Self::min_partial_rollover_value] is configured.
    /// This will typically be shorter than
    /// [Self::fixed_term_rollover_window_duration_seconds], acting as a
    /// fallback if a fixed reserve liquidity remains unavailable for
    /// considerable time.
    pub open_term_rollover_window_duration_seconds: u64,
    /// Minimum dollar value for a partial rollover into a different reserve.
    /// When the achievable rollover amount is below this threshold (and it's
    /// not a full rollover), the rollover is rejected.
    /// In full units of the quote currency (e.g. `2` means "$2").
    pub min_partial_rollover_value: u64,
    /// The time that must pass before an entire expired debt becomes
    /// liquidatable. For example:
    /// Let's assume this duration is configured as 100 seconds; then:
    /// - right after fixed-term debt expiration, effectively no debt can be
    ///   liquidated.
    /// - 30 seconds after expiration, we allow to 30% of the expired debt to be
    ///   liquidated
    /// - to be specific: at this point in time, we "protect" from liquidation
    ///   70% of the
    ///
    /// [ObligationLiquidity::borrowed_amount_at_expiration] (regardless of how
    /// much interest was accrued or how much debt was repaid while
    /// expired).
    /// - 100 seconds after expiration we allow the entire debt to be
    ///   liquidated.
    ///
    /// Only effective when
    /// [Self::obligation_borrow_debt_term_liquidation_enabled]. Motivation
    /// note: this throttling feature gives an opportunity to execute a
    /// configured auto-rollover (after a partial liquidation brings the
    /// debt size down so that there is enough available liquidity in some
    /// compatible reserve). When zeroed, an entire expired debt can be
    /// liquidated right after expiration (i.e. no throttling).
    pub term_based_full_liquidation_duration_secs: u64,
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub padding1: [u64; 158],
}

impl LendingMarket {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [246, 114, 50, 98, 72, 157, 28, 120] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
